version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      npm-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
      npm-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
      npm-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
