// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from "@hey-api/client-fetch";
import {
  queryOptions,
  type UseMutationOptions,
  type DefaultError,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  SearchApiStatusData,
  PhmmerApiSearchData,
  PhmmerApiSearchResponse,
  ResultApiGetResultData,
  ResultApiGetResultError,
  ResultApiGetResultResponse,
  TaxonomyApiGetData,
} from "../types.gen";
import {
  client,
  searchApiStatus,
  phmmerApiSearch,
  resultApiGetResult,
  taxonomyApiGet,
} from "../sdk.gen";

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const searchApiStatusQueryKey = (
  options: Options<SearchApiStatusData>,
) => [createQueryKey("searchApiStatus", options)];

export const searchApiStatusOptions = (
  options: Options<SearchApiStatusData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchApiStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchApiStatusQueryKey(options),
  });
};

export const phmmerApiSearchQueryKey = (
  options: Options<PhmmerApiSearchData>,
) => [createQueryKey("phmmerApiSearch", options)];

export const phmmerApiSearchOptions = (
  options: Options<PhmmerApiSearchData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await phmmerApiSearch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: phmmerApiSearchQueryKey(options),
  });
};

export const phmmerApiSearchMutation = (
  options?: Partial<Options<PhmmerApiSearchData>>,
) => {
  const mutationOptions: UseMutationOptions<
    PhmmerApiSearchResponse,
    DefaultError,
    Options<PhmmerApiSearchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await phmmerApiSearch({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const resultApiGetResultQueryKey = (
  options: Options<ResultApiGetResultData>,
) => [createQueryKey("resultApiGetResult", options)];

export const resultApiGetResultOptions = (
  options: Options<ResultApiGetResultData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await resultApiGetResult({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: resultApiGetResultQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const resultApiGetResultInfiniteQueryKey = (
  options: Options<ResultApiGetResultData>,
): QueryKey<Options<ResultApiGetResultData>> => [
  createQueryKey("resultApiGetResult", options, true),
];

export const resultApiGetResultInfiniteOptions = (
  options: Options<ResultApiGetResultData>,
) => {
  return infiniteQueryOptions<
    ResultApiGetResultResponse,
    ResultApiGetResultError,
    InfiniteData<ResultApiGetResultResponse>,
    QueryKey<Options<ResultApiGetResultData>>,
    | number
    | Pick<
        QueryKey<Options<ResultApiGetResultData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ResultApiGetResultData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await resultApiGetResult({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: resultApiGetResultInfiniteQueryKey(options),
    },
  );
};

export const taxonomyApiGetQueryKey = (
  options?: Options<TaxonomyApiGetData>,
) => [createQueryKey("taxonomyApiGet", options)];

export const taxonomyApiGetOptions = (
  options?: Options<TaxonomyApiGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await taxonomyApiGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: taxonomyApiGetQueryKey(options),
  });
};
