// This file is auto-generated by @hey-api/openapi-ts

import {
    type DefaultError,
    type InfiniteData,
    infiniteQueryOptions,
    queryOptions,
    type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
    architectureApiGetAllArchitectures,
    architectureApiGetAnnotations,
    architectureApiGetArchitectureName,
    architectureApiGetDomainArchitectures,
    downloadApiDownloadFile,
    downloadApiGenerateFile,
    downloadApiGetDownloads,
    type Options,
    resultApiGetDomains,
    resultApiGetResult,
    searchApiGetDatabases,
    searchApiGetJobDetails,
    searchApiGetJobQuery,
    searchApiGetJobs,
    searchApiSearch,
    searchApiUpdateSearch,
    taxonomyApiGet,
    taxonomyApiGetTaxonomy,
    taxonomyApiGetTaxonomyDistribution,
    taxonomyApiGetTaxonomyTree,
    taxonomyApiSearchTaxonomy,
} from "../sdk.gen";
import type {
    ArchitectureApiGetAllArchitecturesData,
    ArchitectureApiGetAllArchitecturesResponse,
    ArchitectureApiGetAnnotationsData,
    ArchitectureApiGetAnnotationsResponse,
    ArchitectureApiGetArchitectureNameData,
    ArchitectureApiGetArchitectureNameResponse,
    ArchitectureApiGetDomainArchitecturesData,
    ArchitectureApiGetDomainArchitecturesResponse,
    DownloadApiDownloadFileData,
    DownloadApiGenerateFileData,
    DownloadApiGenerateFileResponse,
    DownloadApiGetDownloadsData,
    DownloadApiGetDownloadsResponse,
    ResultApiGetDomainsData,
    ResultApiGetDomainsResponse,
    ResultApiGetResultData,
    ResultApiGetResultResponse,
    SearchApiGetDatabasesData,
    SearchApiGetDatabasesResponse,
    SearchApiGetJobDetailsData,
    SearchApiGetJobDetailsResponse,
    SearchApiGetJobQueryData,
    SearchApiGetJobsData,
    SearchApiGetJobsResponse,
    SearchApiSearchData,
    SearchApiSearchError,
    SearchApiSearchResponse,
    SearchApiUpdateSearchData,
    SearchApiUpdateSearchError,
    SearchApiUpdateSearchResponse,
    TaxonomyApiGetData,
    TaxonomyApiGetTaxonomyData,
    TaxonomyApiGetTaxonomyDistributionData,
    TaxonomyApiGetTaxonomyDistributionResponse,
    TaxonomyApiGetTaxonomyResponse,
    TaxonomyApiGetTaxonomyTreeData,
    TaxonomyApiGetTaxonomyTreeResponse,
    TaxonomyApiSearchTaxonomyData,
    TaxonomyApiSearchTaxonomyResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    },
];

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const architectureApiGetArchitectureNameQueryKey = (options: Options<ArchitectureApiGetArchitectureNameData>) =>
    createQueryKey("architectureApiGetArchitectureName", options);

/**
 * Get Architecture Name
 */
export const architectureApiGetArchitectureNameOptions = (options: Options<ArchitectureApiGetArchitectureNameData>) =>
    queryOptions<
        ArchitectureApiGetArchitectureNameResponse,
        DefaultError,
        ArchitectureApiGetArchitectureNameResponse,
        ReturnType<typeof architectureApiGetArchitectureNameQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await architectureApiGetArchitectureName({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: architectureApiGetArchitectureNameQueryKey(options),
    });

export const architectureApiGetDomainArchitecturesQueryKey = (
    options: Options<ArchitectureApiGetDomainArchitecturesData>,
) => createQueryKey("architectureApiGetDomainArchitectures", options);

/**
 * Get Domain Architectures
 */
export const architectureApiGetDomainArchitecturesOptions = (
    options: Options<ArchitectureApiGetDomainArchitecturesData>,
) =>
    queryOptions<
        ArchitectureApiGetDomainArchitecturesResponse,
        DefaultError,
        ArchitectureApiGetDomainArchitecturesResponse,
        ReturnType<typeof architectureApiGetDomainArchitecturesQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await architectureApiGetDomainArchitectures({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: architectureApiGetDomainArchitecturesQueryKey(options),
    });

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
    queryKey: QueryKey<Options>,
    page: K,
) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...(queryKey[0].body as any),
            ...(page.body as any),
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers,
        };
    }
    if (page.path) {
        params.path = {
            ...(queryKey[0].path as any),
            ...(page.path as any),
        };
    }
    if (page.query) {
        params.query = {
            ...(queryKey[0].query as any),
            ...(page.query as any),
        };
    }
    return params as unknown as typeof page;
};

export const architectureApiGetDomainArchitecturesInfiniteQueryKey = (
    options: Options<ArchitectureApiGetDomainArchitecturesData>,
): QueryKey<Options<ArchitectureApiGetDomainArchitecturesData>> =>
    createQueryKey("architectureApiGetDomainArchitectures", options, true);

/**
 * Get Domain Architectures
 */
export const architectureApiGetDomainArchitecturesInfiniteOptions = (
    options: Options<ArchitectureApiGetDomainArchitecturesData>,
) =>
    infiniteQueryOptions<
        ArchitectureApiGetDomainArchitecturesResponse,
        DefaultError,
        InfiniteData<ArchitectureApiGetDomainArchitecturesResponse>,
        QueryKey<Options<ArchitectureApiGetDomainArchitecturesData>>,
        | number
        | Pick<QueryKey<Options<ArchitectureApiGetDomainArchitecturesData>>[0], "body" | "headers" | "path" | "query">
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<
                    QueryKey<Options<ArchitectureApiGetDomainArchitecturesData>>[0],
                    "body" | "headers" | "path" | "query"
                > =
                    typeof pageParam === "object"
                        ? pageParam
                        : {
                              query: {
                                  page: pageParam,
                              },
                          };
                const params = createInfiniteParams(queryKey, page);
                const { data } = await architectureApiGetDomainArchitectures({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                });
                return data;
            },
            queryKey: architectureApiGetDomainArchitecturesInfiniteQueryKey(options),
        },
    );

export const architectureApiGetAnnotationsQueryKey = (options: Options<ArchitectureApiGetAnnotationsData>) =>
    createQueryKey("architectureApiGetAnnotations", options);

/**
 * Get Annotations
 */
export const architectureApiGetAnnotationsOptions = (options: Options<ArchitectureApiGetAnnotationsData>) =>
    queryOptions<
        ArchitectureApiGetAnnotationsResponse,
        DefaultError,
        ArchitectureApiGetAnnotationsResponse,
        ReturnType<typeof architectureApiGetAnnotationsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await architectureApiGetAnnotations({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: architectureApiGetAnnotationsQueryKey(options),
    });

export const architectureApiGetAllArchitecturesQueryKey = (options: Options<ArchitectureApiGetAllArchitecturesData>) =>
    createQueryKey("architectureApiGetAllArchitectures", options);

/**
 * Get All Architectures
 */
export const architectureApiGetAllArchitecturesOptions = (options: Options<ArchitectureApiGetAllArchitecturesData>) =>
    queryOptions<
        ArchitectureApiGetAllArchitecturesResponse,
        DefaultError,
        ArchitectureApiGetAllArchitecturesResponse,
        ReturnType<typeof architectureApiGetAllArchitecturesQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await architectureApiGetAllArchitectures({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: architectureApiGetAllArchitecturesQueryKey(options),
    });

export const architectureApiGetAllArchitecturesInfiniteQueryKey = (
    options: Options<ArchitectureApiGetAllArchitecturesData>,
): QueryKey<Options<ArchitectureApiGetAllArchitecturesData>> =>
    createQueryKey("architectureApiGetAllArchitectures", options, true);

/**
 * Get All Architectures
 */
export const architectureApiGetAllArchitecturesInfiniteOptions = (
    options: Options<ArchitectureApiGetAllArchitecturesData>,
) =>
    infiniteQueryOptions<
        ArchitectureApiGetAllArchitecturesResponse,
        DefaultError,
        InfiniteData<ArchitectureApiGetAllArchitecturesResponse>,
        QueryKey<Options<ArchitectureApiGetAllArchitecturesData>>,
        | number
        | Pick<QueryKey<Options<ArchitectureApiGetAllArchitecturesData>>[0], "body" | "headers" | "path" | "query">
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<
                    QueryKey<Options<ArchitectureApiGetAllArchitecturesData>>[0],
                    "body" | "headers" | "path" | "query"
                > =
                    typeof pageParam === "object"
                        ? pageParam
                        : {
                              query: {
                                  page: pageParam,
                              },
                          };
                const params = createInfiniteParams(queryKey, page);
                const { data } = await architectureApiGetAllArchitectures({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                });
                return data;
            },
            queryKey: architectureApiGetAllArchitecturesInfiniteQueryKey(options),
        },
    );

export const resultApiGetResultQueryKey = (options: Options<ResultApiGetResultData>) =>
    createQueryKey("resultApiGetResult", options);

/**
 * Get Result
 */
export const resultApiGetResultOptions = (options: Options<ResultApiGetResultData>) =>
    queryOptions<
        ResultApiGetResultResponse,
        DefaultError,
        ResultApiGetResultResponse,
        ReturnType<typeof resultApiGetResultQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resultApiGetResult({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: resultApiGetResultQueryKey(options),
    });

export const resultApiGetResultInfiniteQueryKey = (
    options: Options<ResultApiGetResultData>,
): QueryKey<Options<ResultApiGetResultData>> => createQueryKey("resultApiGetResult", options, true);

/**
 * Get Result
 */
export const resultApiGetResultInfiniteOptions = (options: Options<ResultApiGetResultData>) =>
    infiniteQueryOptions<
        ResultApiGetResultResponse,
        DefaultError,
        InfiniteData<ResultApiGetResultResponse>,
        QueryKey<Options<ResultApiGetResultData>>,
        number | Pick<QueryKey<Options<ResultApiGetResultData>>[0], "body" | "headers" | "path" | "query">
    >(
        // @ts-ignore
        {
            queryFn: async ({ pageParam, queryKey, signal }) => {
                // @ts-ignore
                const page: Pick<QueryKey<Options<ResultApiGetResultData>>[0], "body" | "headers" | "path" | "query"> =
                    typeof pageParam === "object"
                        ? pageParam
                        : {
                              query: {
                                  page: pageParam,
                              },
                          };
                const params = createInfiniteParams(queryKey, page);
                const { data } = await resultApiGetResult({
                    ...options,
                    ...params,
                    signal,
                    throwOnError: true,
                });
                return data;
            },
            queryKey: resultApiGetResultInfiniteQueryKey(options),
        },
    );

export const resultApiGetDomainsQueryKey = (options: Options<ResultApiGetDomainsData>) =>
    createQueryKey("resultApiGetDomains", options);

/**
 * Get Domains
 */
export const resultApiGetDomainsOptions = (options: Options<ResultApiGetDomainsData>) =>
    queryOptions<
        ResultApiGetDomainsResponse,
        DefaultError,
        ResultApiGetDomainsResponse,
        ReturnType<typeof resultApiGetDomainsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resultApiGetDomains({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: resultApiGetDomainsQueryKey(options),
    });

export const searchApiGetDatabasesQueryKey = (options?: Options<SearchApiGetDatabasesData>) =>
    createQueryKey("searchApiGetDatabases", options);

/**
 * Get Databases
 */
export const searchApiGetDatabasesOptions = (options?: Options<SearchApiGetDatabasesData>) =>
    queryOptions<
        SearchApiGetDatabasesResponse,
        DefaultError,
        SearchApiGetDatabasesResponse,
        ReturnType<typeof searchApiGetDatabasesQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchApiGetDatabases({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: searchApiGetDatabasesQueryKey(options),
    });

export const searchApiGetJobDetailsQueryKey = (options: Options<SearchApiGetJobDetailsData>) =>
    createQueryKey("searchApiGetJobDetails", options);

/**
 * Get Job Details
 */
export const searchApiGetJobDetailsOptions = (options: Options<SearchApiGetJobDetailsData>) =>
    queryOptions<
        SearchApiGetJobDetailsResponse,
        DefaultError,
        SearchApiGetJobDetailsResponse,
        ReturnType<typeof searchApiGetJobDetailsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchApiGetJobDetails({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: searchApiGetJobDetailsQueryKey(options),
    });

/**
 * Update Search
 */
export const searchApiUpdateSearchMutation = (
    options?: Partial<Options<SearchApiUpdateSearchData>>,
): UseMutationOptions<
    SearchApiUpdateSearchResponse,
    SearchApiUpdateSearchError,
    Options<SearchApiUpdateSearchData>
> => {
    const mutationOptions: UseMutationOptions<
        SearchApiUpdateSearchResponse,
        SearchApiUpdateSearchError,
        Options<SearchApiUpdateSearchData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await searchApiUpdateSearch({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const searchApiGetJobQueryQueryKey = (options: Options<SearchApiGetJobQueryData>) =>
    createQueryKey("searchApiGetJobQuery", options);

/**
 * Get Job Query
 */
export const searchApiGetJobQueryOptions = (options: Options<SearchApiGetJobQueryData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof searchApiGetJobQueryQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchApiGetJobQuery({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: searchApiGetJobQueryQueryKey(options),
    });

/**
 * Search
 */
export const searchApiSearchMutation = (
    options?: Partial<Options<SearchApiSearchData>>,
): UseMutationOptions<SearchApiSearchResponse, SearchApiSearchError, Options<SearchApiSearchData>> => {
    const mutationOptions: UseMutationOptions<
        SearchApiSearchResponse,
        SearchApiSearchError,
        Options<SearchApiSearchData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await searchApiSearch({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const searchApiGetJobsQueryKey = (options?: Options<SearchApiGetJobsData>) =>
    createQueryKey("searchApiGetJobs", options);

/**
 * Get Jobs
 */
export const searchApiGetJobsOptions = (options?: Options<SearchApiGetJobsData>) =>
    queryOptions<
        SearchApiGetJobsResponse,
        DefaultError,
        SearchApiGetJobsResponse,
        ReturnType<typeof searchApiGetJobsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchApiGetJobs({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: searchApiGetJobsQueryKey(options),
    });

export const taxonomyApiGetQueryKey = (options?: Options<TaxonomyApiGetData>) =>
    createQueryKey("taxonomyApiGet", options);

/**
 * Get
 */
export const taxonomyApiGetOptions = (options?: Options<TaxonomyApiGetData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof taxonomyApiGetQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await taxonomyApiGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: taxonomyApiGetQueryKey(options),
    });

export const taxonomyApiSearchTaxonomyQueryKey = (options: Options<TaxonomyApiSearchTaxonomyData>) =>
    createQueryKey("taxonomyApiSearchTaxonomy", options);

/**
 * Search Taxonomy
 */
export const taxonomyApiSearchTaxonomyOptions = (options: Options<TaxonomyApiSearchTaxonomyData>) =>
    queryOptions<
        TaxonomyApiSearchTaxonomyResponse,
        DefaultError,
        TaxonomyApiSearchTaxonomyResponse,
        ReturnType<typeof taxonomyApiSearchTaxonomyQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await taxonomyApiSearchTaxonomy({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: taxonomyApiSearchTaxonomyQueryKey(options),
    });

export const taxonomyApiGetTaxonomyQueryKey = (options: Options<TaxonomyApiGetTaxonomyData>) =>
    createQueryKey("taxonomyApiGetTaxonomy", options);

/**
 * Get Taxonomy
 */
export const taxonomyApiGetTaxonomyOptions = (options: Options<TaxonomyApiGetTaxonomyData>) =>
    queryOptions<
        TaxonomyApiGetTaxonomyResponse,
        DefaultError,
        TaxonomyApiGetTaxonomyResponse,
        ReturnType<typeof taxonomyApiGetTaxonomyQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await taxonomyApiGetTaxonomy({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: taxonomyApiGetTaxonomyQueryKey(options),
    });

export const taxonomyApiGetTaxonomyTreeQueryKey = (options: Options<TaxonomyApiGetTaxonomyTreeData>) =>
    createQueryKey("taxonomyApiGetTaxonomyTree", options);

/**
 * Get Taxonomy Tree
 */
export const taxonomyApiGetTaxonomyTreeOptions = (options: Options<TaxonomyApiGetTaxonomyTreeData>) =>
    queryOptions<
        TaxonomyApiGetTaxonomyTreeResponse,
        DefaultError,
        TaxonomyApiGetTaxonomyTreeResponse,
        ReturnType<typeof taxonomyApiGetTaxonomyTreeQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await taxonomyApiGetTaxonomyTree({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: taxonomyApiGetTaxonomyTreeQueryKey(options),
    });

export const taxonomyApiGetTaxonomyDistributionQueryKey = (options: Options<TaxonomyApiGetTaxonomyDistributionData>) =>
    createQueryKey("taxonomyApiGetTaxonomyDistribution", options);

/**
 * Get Taxonomy Distribution
 */
export const taxonomyApiGetTaxonomyDistributionOptions = (options: Options<TaxonomyApiGetTaxonomyDistributionData>) =>
    queryOptions<
        TaxonomyApiGetTaxonomyDistributionResponse,
        DefaultError,
        TaxonomyApiGetTaxonomyDistributionResponse,
        ReturnType<typeof taxonomyApiGetTaxonomyDistributionQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await taxonomyApiGetTaxonomyDistribution({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: taxonomyApiGetTaxonomyDistributionQueryKey(options),
    });

export const downloadApiDownloadFileQueryKey = (options: Options<DownloadApiDownloadFileData>) =>
    createQueryKey("downloadApiDownloadFile", options);

/**
 * Download File
 */
export const downloadApiDownloadFileOptions = (options: Options<DownloadApiDownloadFileData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof downloadApiDownloadFileQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await downloadApiDownloadFile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: downloadApiDownloadFileQueryKey(options),
    });

/**
 * Generate File
 */
export const downloadApiGenerateFileMutation = (
    options?: Partial<Options<DownloadApiGenerateFileData>>,
): UseMutationOptions<DownloadApiGenerateFileResponse, DefaultError, Options<DownloadApiGenerateFileData>> => {
    const mutationOptions: UseMutationOptions<
        DownloadApiGenerateFileResponse,
        DefaultError,
        Options<DownloadApiGenerateFileData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await downloadApiGenerateFile({
                ...options,
                ...fnOptions,
                throwOnError: true,
            });
            return data;
        },
    };
    return mutationOptions;
};

export const downloadApiGetDownloadsQueryKey = (options: Options<DownloadApiGetDownloadsData>) =>
    createQueryKey("downloadApiGetDownloads", options);

/**
 * Get Downloads
 */
export const downloadApiGetDownloadsOptions = (options: Options<DownloadApiGetDownloadsData>) =>
    queryOptions<
        DownloadApiGetDownloadsResponse,
        DefaultError,
        DownloadApiGetDownloadsResponse,
        ReturnType<typeof downloadApiGetDownloadsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await downloadApiGetDownloads({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            });
            return data;
        },
        queryKey: downloadApiGetDownloadsQueryKey(options),
    });
