// This file is auto-generated by @hey-api/openapi-ts

export const ArchitectureSchemaSchema = {
    properties: {
        sequence_accession: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sequence Accession'
        },
        sequence_external_link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sequence External Link'
        },
        names: {
            title: 'Names',
            type: 'string'
        },
        score: {
            title: 'Score',
            type: 'integer'
        },
        graphics: {
            title: 'Graphics',
            type: 'object'
        },
        accessions: {
            title: 'Accessions',
            type: 'string'
        }
    },
    required: ['names', 'score', 'graphics', 'accessions'],
    title: 'ArchitectureSchema',
    type: 'object'
} as const;

export const ArchitectureQuerySchemaSchema = {
    properties: {
        page: {
            default: 1,
            exclusiveMinimum: 0,
            title: 'Page',
            type: 'integer'
        },
        page_size: {
            default: 50,
            exclusiveMinimum: 0,
            title: 'Page Size',
            type: 'integer'
        }
    },
    title: 'ArchitectureQuerySchema',
    type: 'object'
} as const;

export const ArchitectureAggregationSchemaSchema = {
    properties: {
        count: {
            title: 'Count',
            type: 'integer'
        },
        architecture: {
            '$ref': '#/components/schemas/ArchitectureSchema'
        }
    },
    required: ['count', 'architecture'],
    title: 'ArchitectureAggregationSchema',
    type: 'object'
} as const;

export const ArchitectureResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        architectures: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ArchitectureAggregationSchema'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Architectures'
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        }
    },
    required: ['status'],
    title: 'ArchitectureResponseSchema',
    type: 'object'
} as const;

export const AnnotationSchema = {
    properties: {
        length: {
            title: 'Length',
            type: 'integer'
        },
        regions: {
            items: {
                '$ref': '#/components/schemas/Region'
            },
            title: 'Regions',
            type: 'array'
        }
    },
    required: ['length', 'regions'],
    title: 'Annotation',
    type: 'object'
} as const;

export const ArchitectureAnnotationsResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        annotations: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Annotation'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotations'
        }
    },
    required: ['status'],
    title: 'ArchitectureAnnotationsResponseSchema',
    type: 'object'
} as const;

export const RegionSchema = {
    properties: {
        color: {
            default: '',
            title: 'Color',
            type: 'string'
        },
        end_style: {
            default: 'curved',
            title: 'End Style',
            type: 'string'
        },
        start_style: {
            default: 'curved',
            title: 'Start Style',
            type: 'string'
        },
        display: {
            default: true,
            title: 'Display',
            type: 'boolean'
        },
        href: {
            default: '',
            title: 'Href',
            type: 'string'
        },
        clan: {
            default: '',
            title: 'Clan',
            type: 'string'
        },
        metadata: {
            additionalProperties: true,
            default: {},
            title: 'Metadata',
            type: 'object'
        },
        type: {
            default: 'pfam',
            title: 'Type',
            type: 'string'
        },
        text: {
            title: 'Text',
            type: 'string'
        },
        model_length: {
            title: 'Model Length',
            type: 'integer'
        },
        model_start: {
            title: 'Model Start',
            type: 'integer'
        },
        model_end: {
            title: 'Model End',
            type: 'integer'
        },
        start: {
            title: 'Start',
            type: 'integer'
        },
        end: {
            title: 'End',
            type: 'integer'
        },
        ali_start: {
            title: 'Ali Start',
            type: 'integer'
        },
        ali_end: {
            title: 'Ali End',
            type: 'integer'
        }
    },
    required: ['text', 'model_length', 'model_start', 'model_end', 'start', 'end', 'ali_start', 'ali_end'],
    title: 'Region',
    type: 'object'
} as const;

export const ArchitectureListResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        architectures: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ArchitectureSchema'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Architectures'
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        }
    },
    required: ['status', 'architectures'],
    title: 'ArchitectureListResponseSchema',
    type: 'object'
} as const;

export const ResultQuerySchemaSchema = {
    properties: {
        page: {
            default: 1,
            exclusiveMinimum: 0,
            title: 'Page',
            type: 'integer'
        },
        page_size: {
            default: 50,
            exclusiveMinimum: 0,
            title: 'Page Size',
            type: 'integer'
        },
        taxonomy_ids: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taxonomy Ids'
        },
        architecture: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Architecture'
        },
        with_domains: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            default: false,
            title: 'With Domains'
        }
    },
    title: 'ResultQuerySchema',
    type: 'object'
} as const;

export const BatchResponseSchemaSchema = {
    properties: {
        id: {
            format: 'uuid4',
            title: 'Id',
            type: 'string'
        },
        query_name: {
            title: 'Query Name',
            type: 'string'
        },
        status: {
            title: 'Status',
            type: 'string'
        }
    },
    required: ['id', 'query_name', 'status'],
    title: 'BatchResponseSchema',
    type: 'object'
} as const;

export const HmmdSearchStatsSchema = {
    additionalProperties: true,
    type: 'object'
} as const;

export const JackhmmerResponseSchemaSchema = {
    properties: {
        id: {
            format: 'uuid4',
            title: 'Id',
            type: 'string'
        },
        status: {
            title: 'Status',
            type: 'string'
        },
        iteration: {
            title: 'Iteration',
            type: 'integer'
        },
        convergence_stats: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Convergence Stats'
        }
    },
    required: ['id', 'status', 'iteration', 'convergence_stats'],
    title: 'JackhmmerResponseSchema',
    type: 'object'
} as const;

export const P7HitSchema = {
    additionalProperties: true,
    type: 'object'
} as const;

export const ResultSchema = {
    properties: {
        stats: {
            '$ref': '#/components/schemas/HmmdSearchStats'
        },
        hits: {
            items: {
                '$ref': '#/components/schemas/P7Hit'
            },
            title: 'Hits',
            type: 'array'
        }
    },
    required: ['stats', 'hits'],
    title: 'Result',
    type: 'object'
} as const;

export const ResultResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Result'
                },
                {
                    type: 'null'
                }
            ]
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        }
    },
    required: ['status'],
    title: 'ResultResponseSchema',
    type: 'object'
} as const;

export const AlignmentQuerySchemaSchema = {
    properties: {
        index: {
            default: 0,
            minimum: 0,
            title: 'Index',
            type: 'integer'
        }
    },
    title: 'AlignmentQuerySchema',
    type: 'object'
} as const;

export const AlignmentResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        domains: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/P7Domain'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domains'
        }
    },
    required: ['status', 'domains'],
    title: 'AlignmentResponseSchema',
    type: 'object'
} as const;

export const P7DomainSchema = {
    additionalProperties: true,
    type: 'object'
} as const;

export const DatabaseResponseSchemaSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    maxLength: 32,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        type: {
            default: 'seq',
            maxLength: 16,
            title: 'Type',
            type: 'string'
        },
        status: {
            default: 'enabled',
            maxLength: 16,
            title: 'Status',
            type: 'string'
        },
        name: {
            maxLength: 32,
            title: 'Name',
            type: 'string'
        },
        version: {
            maxLength: 32,
            title: 'Version',
            type: 'string'
        },
        release_date: {
            format: 'date',
            title: 'Release Date',
            type: 'string'
        },
        order: {
            default: -1,
            title: 'Order',
            type: 'integer'
        }
    },
    required: ['name', 'version'],
    title: 'DatabaseResponseSchema',
    type: 'object'
} as const;

export const JobDetailsResponseSchemaSchema = {
    properties: {
        task: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaskResultSchema'
                },
                {
                    type: 'null'
                }
            ]
        },
        database: {
            '$ref': '#/components/schemas/DatabaseResponseSchema'
        },
        iteration: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Iteration'
        },
        next_job_id: {
            anyOf: [
                {
                    format: 'uuid4',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Job Id'
        },
        previous_job_id: {
            anyOf: [
                {
                    format: 'uuid4',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Job Id'
        },
        parent_job_id: {
            anyOf: [
                {
                    format: 'uuid4',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Job Id'
        },
        include: {
            items: {
                type: 'integer'
            },
            title: 'Include',
            type: 'array'
        },
        exclude: {
            items: {
                type: 'integer'
            },
            title: 'Exclude',
            type: 'array'
        },
        id: {
            anyOf: [
                {
                    format: 'uuid',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        algo: {
            default: 'phmmer',
            maxLength: 16,
            title: 'Algo',
            type: 'string'
        },
        input: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input'
        },
        input_type: {
            default: 'sequence',
            maxLength: 16,
            title: 'Input Type',
            type: 'string'
        },
        calculated_input: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Calculated Input'
        },
        threshold: {
            default: 'evalue',
            maxLength: 16,
            title: 'Threshold',
            type: 'string'
        },
        E: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 1,
            title: 'E'
        },
        domE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 1,
            title: 'domE'
        },
        T: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 7,
            title: 'T'
        },
        domT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 5,
            title: 'domT'
        },
        incE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.01,
            title: 'incE'
        },
        incdomE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.03,
            title: 'incdomE'
        },
        incT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 25,
            title: 'incT'
        },
        incdomT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 22,
            title: 'incdomT'
        },
        include_taxonomy: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Include Taxonomy'
        },
        exclude_taxonomy: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exclude Taxonomy'
        },
        popen: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.02,
            title: 'Popen'
        },
        pextend: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.4,
            title: 'Pextend'
        },
        mx: {
            anyOf: [
                {
                    maxLength: 16,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: 'BLOSUM62',
            title: 'Mx'
        },
        with_taxonomy: {
            default: false,
            title: 'With Taxonomy',
            type: 'boolean'
        },
        with_architecture: {
            default: false,
            title: 'With Architecture',
            type: 'boolean'
        },
        exclude_all: {
            default: false,
            title: 'Exclude All',
            type: 'boolean'
        },
        iterations: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Iterations'
        },
        date_submitted: {
            anyOf: [
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Submitted'
        },
        number_of_hits: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number Of Hits'
        },
        number_of_included: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number Of Included'
        },
        number_of_gained: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number Of Gained'
        },
        number_of_dropped: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number Of Dropped'
        },
        number_of_lost: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number Of Lost'
        },
        first_gained_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Gained Index'
        },
        email_address: {
            anyOf: [
                {
                    maxLength: 254,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email Address'
        }
    },
    required: ['task', 'database', 'iteration', 'next_job_id', 'previous_job_id', 'parent_job_id', 'include', 'exclude'],
    title: 'JobDetailsResponseSchema',
    type: 'object'
} as const;

export const TaskResultSchemaSchema = {
    properties: {
        status: {
            default: 'PENDING',
            description: 'Current state of the task being run',
            maxLength: 50,
            title: 'Task State',
            type: 'string'
        },
        date_created: {
            description: 'Datetime field when the task result was created in UTC',
            format: 'date-time',
            title: 'Created DateTime',
            type: 'string'
        },
        date_done: {
            description: 'Datetime field when the task was completed in UTC',
            format: 'date-time',
            title: 'Completed DateTime',
            type: 'string'
        }
    },
    required: ['date_created', 'date_done'],
    title: 'TaskResultSchema',
    type: 'object'
} as const;

export const ValidationErrorDetailSchemaSchema = {
    properties: {
        type: {
            title: 'Type',
            type: 'string'
        },
        loc: {
            items: {
                type: 'string'
            },
            title: 'Loc',
            type: 'array'
        },
        msg: {
            title: 'Msg',
            type: 'string'
        }
    },
    required: ['type', 'loc', 'msg'],
    title: 'ValidationErrorDetailSchema',
    type: 'object'
} as const;

export const ValidationErrorSchemaSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationErrorDetailSchema'
            },
            title: 'Detail',
            type: 'array'
        }
    },
    required: ['detail'],
    title: 'ValidationErrorSchema',
    type: 'object'
} as const;

export const SearchPatchSchemaSchema = {
    properties: {
        email_address: {
            anyOf: [
                {
                    format: 'email',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email Address'
        }
    },
    title: 'SearchPatchSchema',
    type: 'object'
} as const;

export const AlgoChoicesSchema = {
    enum: ['phmmer', 'hmmsearch', 'hmmscan', 'jackhmmer'],
    title: 'AlgoChoices',
    type: 'string'
} as const;

export const SearchResponseSchemaSchema = {
    properties: {
        id: {
            format: 'uuid4',
            title: 'Id',
            type: 'string'
        }
    },
    required: ['id'],
    title: 'SearchResponseSchema',
    type: 'object'
} as const;

export const SearchRequestSchemaSchema = {
    properties: {
        input: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    format: 'uuid4',
                    type: 'string'
                }
            ],
            title: 'Input'
        },
        input_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Type'
        },
        database: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Database'
        },
        include: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: [],
            title: 'Include'
        },
        exclude: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: [],
            title: 'Exclude'
        },
        include_taxonomy: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: [],
            title: 'Include Taxonomy'
        },
        exclude_taxonomy: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: [],
            title: 'Exclude Taxonomy'
        },
        threshold: {
            anyOf: [
                {
                    maxLength: 16,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: 'evalue',
            title: 'Threshold'
        },
        E: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 1,
            title: 'E'
        },
        domE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 1,
            title: 'domE'
        },
        T: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 7,
            title: 'T'
        },
        domT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 5,
            title: 'domT'
        },
        incE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.01,
            title: 'incE'
        },
        incdomE: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.03,
            title: 'incdomE'
        },
        incT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 25,
            title: 'incT'
        },
        incdomT: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 22,
            title: 'incdomT'
        },
        popen: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.02,
            title: 'Popen'
        },
        pextend: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: 0.4,
            title: 'Pextend'
        },
        mx: {
            anyOf: [
                {
                    maxLength: 16,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: 'BLOSUM62',
            title: 'Mx'
        },
        with_taxonomy: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            default: false,
            title: 'With Taxonomy'
        },
        with_architecture: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            default: false,
            title: 'With Architecture'
        },
        iterations: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Iterations'
        },
        exclude_all: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            default: false,
            title: 'Exclude All'
        },
        email_address: {
            anyOf: [
                {
                    maxLength: 254,
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email Address'
        }
    },
    required: ['input'],
    title: 'SearchRequestSchema',
    type: 'object'
} as const;

export const JobsResponseSchemaSchema = {
    properties: {
        task: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaskResultSchema'
                },
                {
                    type: 'null'
                }
            ]
        },
        query_name: {
            title: 'Query Name',
            type: 'string'
        },
        id: {
            anyOf: [
                {
                    format: 'uuid',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        algo: {
            default: 'phmmer',
            maxLength: 16,
            title: 'Algo',
            type: 'string'
        },
        date_submitted: {
            anyOf: [
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Submitted'
        }
    },
    required: ['task', 'query_name'],
    title: 'JobsResponseSchema',
    type: 'object'
} as const;

export const TaxonomyResponseSchemaSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            maxLength: 255,
            title: 'Name',
            type: 'string'
        },
        rank: {
            maxLength: 255,
            title: 'Rank',
            type: 'string'
        },
        lft: {
            title: 'Lft',
            type: 'integer'
        },
        rgt: {
            title: 'Rgt',
            type: 'integer'
        },
        depth: {
            title: 'Depth',
            type: 'integer'
        }
    },
    required: ['name', 'rank', 'lft', 'rgt', 'depth'],
    title: 'TaxonomyResponseSchema',
    type: 'object'
} as const;

export const TaxonomyTreeSchema = {
    properties: {
        id: {
            title: 'Id',
            type: 'integer'
        },
        name: {
            title: 'Name',
            type: 'string'
        },
        hitcount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hitcount'
        },
        hitdist: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hitdist'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/TaxonomyTree'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        }
    },
    required: ['id', 'name', 'hitcount', 'hitdist', 'children'],
    title: 'TaxonomyTree',
    type: 'object'
} as const;

export const TaxonomyTreeResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        tree: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaxonomyTree'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: ['status'],
    title: 'TaxonomyTreeResponseSchema',
    type: 'object'
} as const;

export const TaxonomyDistributionGraphSchema = {
    properties: {
        data: {
            items: {
                items: {
                    type: 'integer'
                },
                type: 'array'
            },
            title: 'Data',
            type: 'array'
        },
        labels: {
            items: {
                type: 'string'
            },
            title: 'Labels',
            type: 'array'
        },
        categories: {
            items: {
                type: 'string'
            },
            title: 'Categories',
            type: 'array'
        },
        colors: {
            items: {
                type: 'string'
            },
            title: 'Colors',
            type: 'array'
        }
    },
    required: ['data', 'labels', 'categories', 'colors'],
    title: 'TaxonomyDistributionGraph',
    type: 'object'
} as const;

export const TaxonomyDistributionResponseSchemaSchema = {
    properties: {
        status: {
            title: 'Status',
            type: 'string'
        },
        graph: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaxonomyDistributionGraph'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: ['status'],
    title: 'TaxonomyDistributionResponseSchema',
    type: 'object'
} as const;

export const DownloadsQuerySchemaSchema = {
    properties: {
        taxonomy_ids: {
            items: {
                type: 'integer'
            },
            title: 'Taxonomy Ids',
            type: 'array'
        },
        architecture: {
            title: 'Architecture',
            type: 'string'
        }
    },
    title: 'DownloadsQuerySchema',
    type: 'object'
} as const;

export const DownloadsResponseSchemaSchema = {
    properties: {
        format: {
            title: 'Format',
            type: 'string'
        },
        name: {
            title: 'Name',
            type: 'string'
        },
        description: {
            title: 'Description',
            type: 'string'
        },
        status: {
            title: 'Status',
            type: 'string'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        }
    },
    required: ['format', 'name', 'description', 'status', 'url', 'size'],
    title: 'DownloadsResponseSchema',
    type: 'object'
} as const;