// This file is auto-generated by @hey-api/openapi-ts

export const HmmerJobStatusSchemaSchema = {
  properties: {
    id: {
      description: "The id of the job",
      format: "uuid4",
      title: "Id",
      type: "string",
    },
    status: {
      description: "The status of the job",
      title: "Status",
      type: "string",
    },
    result_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "URL to get the result of the job",
      title: "Result Url",
    },
    error_message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      description: "The error message of the job",
      title: "Error Message",
    },
  },
  required: ["id", "status", "result_url", "error_message"],
  title: "HmmerJobStatusSchema",
  type: "object",
} as const;

export const HmmerJobCreatedSchemaSchema = {
  properties: {
    id: {
      description: "The id of the job",
      format: "uuid4",
      title: "Id",
      type: "string",
    },
    status: {
      description: "The status of the job",
      title: "Status",
      type: "string",
    },
    status_url: {
      description: "URL to get the status of the job",
      title: "Status Url",
      type: "string",
    },
  },
  required: ["id", "status", "status_url"],
  title: "HmmerJobCreatedSchema",
  type: "object",
} as const;

export const PhmmerJobSchemaSchema = {
  properties: {
    popen: {
      anyOf: [
        {
          exclusiveMaximum: 0.5,
          minimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 0.02,
      title: "Popen",
    },
    pextend: {
      anyOf: [
        {
          exclusiveMaximum: 1,
          minimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 0.4,
      title: "Pextend",
    },
    mx: {
      anyOf: [
        {
          enum: [
            "BLOSUM62",
            "BLOSUM45",
            "BLOSUM90",
            "PAM30",
            "PAM70",
            "PAM250",
          ],
          type: "string",
        },
        {
          type: "null",
        },
      ],
      default: "BLOSUM62",
      title: "Mx",
    },
    threshold: {
      default: "evalue",
      enum: ["evalue", "bitscore"],
      title: "Threshold",
      type: "string",
    },
    incE: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          maximum: 10,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 0.01,
      title: "Ince",
    },
    incdomE: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          maximum: 10,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 0.03,
      title: "Incdome",
    },
    E: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          maximum: 10,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 1,
      title: "E",
    },
    domE: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          maximum: 10,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 1,
      title: "Dome",
    },
    incT: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 25,
      title: "Inct",
    },
    incdomT: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 22,
      title: "Incdomt",
    },
    T: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 7,
      title: "T",
    },
    domT: {
      anyOf: [
        {
          exclusiveMinimum: 0,
          type: "number",
        },
        {
          type: "null",
        },
      ],
      default: 5,
      title: "Domt",
    },
    seq: {
      minLength: 1,
      title: "Seq",
      type: "string",
    },
    seqdb: {
      title: "Seqdb",
      type: "string",
    },
  },
  required: ["seq", "seqdb"],
  title: "PhmmerJobSchema",
  type: "object",
} as const;

export const QuerySchemaSchema = {
  properties: {
    limit: {
      default: 10,
      exclusiveMinimum: 0,
      title: "Limit",
      type: "integer",
    },
    offset: {
      default: 0,
      minimum: 0,
      title: "Offset",
      type: "integer",
    },
  },
  title: "QuerySchema",
  type: "object",
} as const;

export const AlignmentSchema = {
  properties: {
    hmm_accession: {
      title: "Hmm Accession",
      type: "string",
    },
    hmm_from: {
      title: "Hmm From",
      type: "integer",
    },
    hmm_length: {
      title: "Hmm Length",
      type: "integer",
    },
    hmm_name: {
      title: "Hmm Name",
      type: "string",
    },
    hmm_sequence: {
      title: "Hmm Sequence",
      type: "string",
    },
    hmm_to: {
      title: "Hmm To",
      type: "integer",
    },
    identity_sequence: {
      title: "Identity Sequence",
      type: "string",
    },
    target_from: {
      title: "Target From",
      type: "integer",
    },
    target_length: {
      title: "Target Length",
      type: "integer",
    },
    target_name: {
      title: "Target Name",
      type: "string",
    },
    target_sequence: {
      title: "Target Sequence",
      type: "string",
    },
    target_to: {
      title: "Target To",
      type: "integer",
    },
  },
  required: [
    "hmm_accession",
    "hmm_from",
    "hmm_length",
    "hmm_name",
    "hmm_sequence",
    "hmm_to",
    "identity_sequence",
    "target_from",
    "target_length",
    "target_name",
    "target_sequence",
    "target_to",
  ],
  title: "Alignment",
  type: "object",
} as const;

export const DomainSchema = {
  properties: {
    alignment: {
      $ref: "#/components/schemas/Alignment",
    },
    bias: {
      title: "Bias",
      type: "number",
    },
    c_evalue: {
      title: "C Evalue",
      type: "number",
    },
    correction: {
      title: "Correction",
      type: "number",
    },
    env_from: {
      title: "Env From",
      type: "integer",
    },
    env_to: {
      title: "Env To",
      type: "integer",
    },
    envelope_score: {
      title: "Envelope Score",
      type: "number",
    },
    i_evalue: {
      title: "I Evalue",
      type: "number",
    },
    included: {
      title: "Included",
      type: "boolean",
    },
    pvalue: {
      title: "Pvalue",
      type: "number",
    },
    reported: {
      title: "Reported",
      type: "boolean",
    },
    score: {
      title: "Score",
      type: "number",
    },
  },
  required: [
    "alignment",
    "bias",
    "c_evalue",
    "correction",
    "env_from",
    "env_to",
    "envelope_score",
    "i_evalue",
    "included",
    "pvalue",
    "reported",
    "score",
  ],
  title: "Domain",
  type: "object",
} as const;

export const DomainsSchema = {
  properties: {
    included: {
      items: {
        $ref: "#/components/schemas/Domain",
      },
      title: "Included",
      type: "array",
    },
    reported: {
      items: {
        $ref: "#/components/schemas/Domain",
      },
      title: "Reported",
      type: "array",
    },
  },
  required: ["included", "reported"],
  title: "Domains",
  type: "object",
} as const;

export const HitSchema = {
  properties: {
    bias: {
      title: "Bias",
      type: "number",
    },
    domains: {
      $ref: "#/components/schemas/Domains",
    },
    dropped: {
      title: "Dropped",
      type: "boolean",
    },
    duplicate: {
      title: "Duplicate",
      type: "boolean",
    },
    evalue: {
      title: "Evalue",
      type: "number",
    },
    included: {
      title: "Included",
      type: "boolean",
    },
    length: {
      title: "Length",
      type: "integer",
    },
    name: {
      title: "Name",
      type: "string",
    },
    new: {
      title: "New",
      type: "boolean",
    },
    pre_score: {
      title: "Pre Score",
      type: "number",
    },
    pvalue: {
      title: "Pvalue",
      type: "number",
    },
    reported: {
      title: "Reported",
      type: "boolean",
    },
    score: {
      title: "Score",
      type: "number",
    },
    sum_score: {
      title: "Sum Score",
      type: "number",
    },
    metadata: {
      $ref: "#/components/schemas/Metadata",
    },
  },
  required: [
    "bias",
    "domains",
    "dropped",
    "duplicate",
    "evalue",
    "included",
    "length",
    "name",
    "new",
    "pre_score",
    "pvalue",
    "reported",
    "score",
    "sum_score",
    "metadata",
  ],
  title: "Hit",
  type: "object",
} as const;

export const MetadataSchema = {
  properties: {
    structures: {
      default: [],
      items: {
        $ref: "#/components/schemas/Structure",
      },
      title: "Structures",
      type: "array",
    },
    taxonomy_id: {
      title: "Taxonomy Id",
      type: "integer",
    },
    architecture_checksum: {
      title: "Architecture Checksum",
      type: "integer",
    },
    architecture_score: {
      title: "Architecture Score",
      type: "integer",
    },
    architecture: {
      title: "Architecture",
      type: "string",
    },
    accession: {
      title: "Accession",
      type: "string",
    },
    identifier: {
      title: "Identifier",
      type: "string",
    },
    description: {
      title: "Description",
      type: "string",
    },
    uniprot_accession: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Uniprot Accession",
    },
    uniprot_identifier: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Uniprot Identifier",
    },
    kingdom: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Kingdom",
    },
    phylum: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Phylum",
    },
    species: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Species",
    },
    external_link: {
      title: "External Link",
      type: "string",
    },
    taxonomy_link: {
      title: "Taxonomy Link",
      type: "string",
    },
  },
  required: [
    "taxonomy_id",
    "architecture_checksum",
    "architecture_score",
    "architecture",
    "accession",
    "identifier",
    "description",
    "uniprot_accession",
    "uniprot_identifier",
    "kingdom",
    "phylum",
    "species",
    "external_link",
    "taxonomy_link",
  ],
  title: "Metadata",
  type: "object",
} as const;

export const ResultSchema = {
  properties: {
    hits: {
      items: {
        $ref: "#/components/schemas/Hit",
      },
      title: "Hits",
      type: "array",
    },
    stats: {
      $ref: "#/components/schemas/Stats",
    },
  },
  required: ["hits", "stats"],
  title: "Result",
  type: "object",
} as const;

export const StatsSchema = {
  properties: {
    E: {
      title: "E",
      type: "number",
    },
    T: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "T",
    },
    Z: {
      title: "Z",
      type: "number",
    },
    bit_cutoffs: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bit Cutoffs",
    },
    domE: {
      title: "Dome",
      type: "number",
    },
    domT: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Domt",
    },
    domZ: {
      title: "Domz",
      type: "number",
    },
    incE: {
      title: "Ince",
      type: "number",
    },
    incT: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Inct",
    },
    incdomE: {
      title: "Incdome",
      type: "number",
    },
    incdomT: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Incdomt",
    },
    searched_models: {
      title: "Searched Models",
      type: "integer",
    },
    searched_nodes: {
      title: "Searched Nodes",
      type: "integer",
    },
    searched_residues: {
      title: "Searched Residues",
      type: "integer",
    },
    searched_sequences: {
      title: "Searched Sequences",
      type: "integer",
    },
    included_hits: {
      title: "Included Hits",
      type: "integer",
    },
    reported_hits: {
      title: "Reported Hits",
      type: "integer",
    },
  },
  required: [
    "E",
    "T",
    "Z",
    "bit_cutoffs",
    "domE",
    "domT",
    "domZ",
    "incE",
    "incT",
    "incdomE",
    "incdomT",
    "searched_models",
    "searched_nodes",
    "searched_residues",
    "searched_sequences",
    "included_hits",
    "reported_hits",
  ],
  title: "Stats",
  type: "object",
} as const;

export const StructureSchema = {
  properties: {
    id: {
      title: "Id",
      type: "string",
    },
    external_link: {
      title: "External Link",
      type: "string",
    },
  },
  required: ["id", "external_link"],
  title: "Structure",
  type: "object",
} as const;

export const MessageSchemaSchema = {
  properties: {
    message: {
      title: "Message",
      type: "string",
    },
  },
  required: ["message"],
  title: "MessageSchema",
  type: "object",
} as const;
