// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  SearchApiStatusData,
  SearchApiStatusResponse,
  PhmmerApiSearchData,
  PhmmerApiSearchResponse,
  ResultApiGetResultData,
  ResultApiGetResultError,
  ResultApiGetResultResponse,
  TaxonomyApiGetData,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Status
 */
export const searchApiStatus = <ThrowOnError extends boolean = false>(
  options: Options<SearchApiStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchApiStatusResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/search/{id}",
  });
};

/**
 * Search
 */
export const phmmerApiSearch = <ThrowOnError extends boolean = false>(
  options: Options<PhmmerApiSearchData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PhmmerApiSearchResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
    url: "/api/v1/search/phmmer",
  });
};

/**
 * Get Result
 */
export const resultApiGetResult = <ThrowOnError extends boolean = false>(
  options: Options<ResultApiGetResultData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ResultApiGetResultResponse,
    ResultApiGetResultError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/result/{id}",
  });
};

/**
 * Get
 */
export const taxonomyApiGet = <ThrowOnError extends boolean = false>(
  options?: Options<TaxonomyApiGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: "/api/v1/taxonomy",
  });
};
