// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
    ArchitectureApiGetArchitectureNameData,
    ArchitectureApiGetArchitectureNameResponses,
    ArchitectureApiGetDomainArchitecturesData,
    ArchitectureApiGetDomainArchitecturesResponses,
    ArchitectureApiGetAnnotationsData,
    ArchitectureApiGetAnnotationsResponses,
    ArchitectureApiGetAllArchitecturesData,
    ArchitectureApiGetAllArchitecturesResponses,
    ResultApiGetResultData,
    ResultApiGetResultResponses,
    ResultApiGetDomainsData,
    ResultApiGetDomainsResponses,
    SearchApiGetDatabasesData,
    SearchApiGetDatabasesResponses,
    SearchApiGetJobDetailsData,
    SearchApiGetJobDetailsResponses,
    SearchApiUpdateSearchData,
    SearchApiUpdateSearchResponses,
    SearchApiUpdateSearchErrors,
    SearchApiGetJobQueryData,
    SearchApiGetJobQueryResponses,
    SearchApiSearchData,
    SearchApiSearchResponses,
    SearchApiSearchErrors,
    SearchApiGetJobsData,
    SearchApiGetJobsResponses,
    TaxonomyApiGetData,
    TaxonomyApiGetResponses,
    TaxonomyApiSearchTaxonomyData,
    TaxonomyApiSearchTaxonomyResponses,
    TaxonomyApiGetTaxonomyData,
    TaxonomyApiGetTaxonomyResponses,
    TaxonomyApiGetTaxonomyTreeData,
    TaxonomyApiGetTaxonomyTreeResponses,
    TaxonomyApiGetTaxonomyDistributionData,
    TaxonomyApiGetTaxonomyDistributionResponses,
    DownloadApiDownloadFileData,
    DownloadApiDownloadFileResponses,
    DownloadApiGenerateFileData,
    DownloadApiGenerateFileResponses,
    DownloadApiGetDownloadsData,
    DownloadApiGetDownloadsResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Architecture Name
 */
export const architectureApiGetArchitectureName = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetArchitectureNameData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ArchitectureApiGetArchitectureNameResponses, unknown, ThrowOnError>({
        url: "/api/v1/architecture/name/{accessions}",
        ...options,
    });
};

/**
 * Get Domain Architectures
 */
export const architectureApiGetDomainArchitectures = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetDomainArchitecturesData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ArchitectureApiGetDomainArchitecturesResponses, unknown, ThrowOnError>(
        {
            url: "/api/v1/architecture/{id}",
            ...options,
        },
    );
};

/**
 * Get Annotations
 */
export const architectureApiGetAnnotations = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetAnnotationsData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ArchitectureApiGetAnnotationsResponses, unknown, ThrowOnError>({
        url: "/api/v1/architecture/{id}/annotations",
        ...options,
    });
};

/**
 * Get All Architectures
 */
export const architectureApiGetAllArchitectures = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetAllArchitecturesData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ArchitectureApiGetAllArchitecturesResponses, unknown, ThrowOnError>({
        url: "/api/v1/architecture/{id}/{accessions}",
        ...options,
    });
};

/**
 * Get Result
 */
export const resultApiGetResult = <ThrowOnError extends boolean = false>(
    options: Options<ResultApiGetResultData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ResultApiGetResultResponses, unknown, ThrowOnError>({
        url: "/api/v1/result/{id}",
        ...options,
    });
};

/**
 * Get Domains
 */
export const resultApiGetDomains = <ThrowOnError extends boolean = false>(
    options: Options<ResultApiGetDomainsData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<ResultApiGetDomainsResponses, unknown, ThrowOnError>({
        url: "/api/v1/result/{id}/domains",
        ...options,
    });
};

/**
 * Get Databases
 */
export const searchApiGetDatabases = <ThrowOnError extends boolean = false>(
    options?: Options<SearchApiGetDatabasesData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<SearchApiGetDatabasesResponses, unknown, ThrowOnError>({
        url: "/api/v1/search/databases",
        ...options,
    });
};

/**
 * Get Job Details
 */
export const searchApiGetJobDetails = <ThrowOnError extends boolean = false>(
    options: Options<SearchApiGetJobDetailsData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<SearchApiGetJobDetailsResponses, unknown, ThrowOnError>({
        url: "/api/v1/search/{id}",
        ...options,
    });
};

/**
 * Update Search
 */
export const searchApiUpdateSearch = <ThrowOnError extends boolean = false>(
    options: Options<SearchApiUpdateSearchData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).patch<
        SearchApiUpdateSearchResponses,
        SearchApiUpdateSearchErrors,
        ThrowOnError
    >({
        url: "/api/v1/search/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Job Query
 */
export const searchApiGetJobQuery = <ThrowOnError extends boolean = false>(
    options: Options<SearchApiGetJobQueryData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<SearchApiGetJobQueryResponses, unknown, ThrowOnError>({
        url: "/api/v1/search/{id}/query",
        ...options,
    });
};

/**
 * Search
 */
export const searchApiSearch = <ThrowOnError extends boolean = false>(
    options: Options<SearchApiSearchData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<SearchApiSearchResponses, SearchApiSearchErrors, ThrowOnError>({
        url: "/api/v1/search/{algo}",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Jobs
 */
export const searchApiGetJobs = <ThrowOnError extends boolean = false>(
    options?: Options<SearchApiGetJobsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<SearchApiGetJobsResponses, unknown, ThrowOnError>({
        url: "/api/v1/search",
        ...options,
    });
};

/**
 * Get
 */
export const taxonomyApiGet = <ThrowOnError extends boolean = false>(
    options?: Options<TaxonomyApiGetData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<TaxonomyApiGetResponses, unknown, ThrowOnError>({
        url: "/api/v1/taxonomy",
        ...options,
    });
};

/**
 * Search Taxonomy
 */
export const taxonomyApiSearchTaxonomy = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiSearchTaxonomyData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<TaxonomyApiSearchTaxonomyResponses, unknown, ThrowOnError>({
        url: "/api/v1/taxonomy/search",
        ...options,
    });
};

/**
 * Get Taxonomy
 */
export const taxonomyApiGetTaxonomy = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<TaxonomyApiGetTaxonomyResponses, unknown, ThrowOnError>({
        url: "/api/v1/taxonomy/{id}",
        ...options,
    });
};

/**
 * Get Taxonomy Tree
 */
export const taxonomyApiGetTaxonomyTree = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyTreeData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<TaxonomyApiGetTaxonomyTreeResponses, unknown, ThrowOnError>({
        url: "/api/v1/taxonomy/{id}/tree",
        ...options,
    });
};

/**
 * Get Taxonomy Distribution
 */
export const taxonomyApiGetTaxonomyDistribution = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyDistributionData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<TaxonomyApiGetTaxonomyDistributionResponses, unknown, ThrowOnError>({
        url: "/api/v1/taxonomy/{id}/distribution",
        ...options,
    });
};

/**
 * Download File
 */
export const downloadApiDownloadFile = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiDownloadFileData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<DownloadApiDownloadFileResponses, unknown, ThrowOnError>({
        url: "/api/v1/download/{id}/{format}",
        ...options,
    });
};

/**
 * Generate File
 */
export const downloadApiGenerateFile = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiGenerateFileData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<DownloadApiGenerateFileResponses, unknown, ThrowOnError>({
        url: "/api/v1/download/{id}/{format}",
        ...options,
    });
};

/**
 * Get Downloads
 */
export const downloadApiGetDownloads = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiGetDownloadsData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<DownloadApiGetDownloadsResponses, unknown, ThrowOnError>({
        url: "/api/v1/download/{id}",
        ...options,
    });
};
