// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch";
import type {
    ArchitectureApiGetArchitectureNameData,
    ArchitectureApiGetArchitectureNameResponse,
    ArchitectureApiGetDomainArchitecturesData,
    ArchitectureApiGetDomainArchitecturesResponse,
    ArchitectureApiGetAnnotationsData,
    ArchitectureApiGetAnnotationsResponse,
    ArchitectureApiGetAllArchitecturesData,
    ArchitectureApiGetAllArchitecturesResponse,
    ResultApiGetResultData,
    ResultApiGetResultResponse,
    ResultApiGetDomainsData,
    ResultApiGetDomainsResponse,
    SearchApiSearchData,
    SearchApiSearchResponse,
    SearchApiGetJobsData,
    SearchApiGetJobsResponse,
    TaxonomyApiGetData,
    TaxonomyApiSearchTaxonomyData,
    TaxonomyApiSearchTaxonomyResponse,
    TaxonomyApiGetTaxonomyData,
    TaxonomyApiGetTaxonomyResponse,
    TaxonomyApiGetTaxonomyTreeData,
    TaxonomyApiGetTaxonomyTreeResponse,
    TaxonomyApiGetTaxonomyDistributionData,
    TaxonomyApiGetTaxonomyDistributionResponse,
    DownloadApiDownloadFileData,
    DownloadApiGenerateFileData,
    DownloadApiGenerateFileResponse,
    DownloadApiGetDownloadsData,
    DownloadApiGetDownloadsResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Get Architecture Name
 */
export const architectureApiGetArchitectureName = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetArchitectureNameData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ArchitectureApiGetArchitectureNameResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/architecture/name/{accessions}",
    });
};

/**
 * Get Domain Architectures
 */
export const architectureApiGetDomainArchitectures = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetDomainArchitecturesData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ArchitectureApiGetDomainArchitecturesResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/architecture/{id}",
    });
};

/**
 * Get Annotations
 */
export const architectureApiGetAnnotations = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetAnnotationsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ArchitectureApiGetAnnotationsResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/architecture/{id}/annotations",
    });
};

/**
 * Get All Architectures
 */
export const architectureApiGetAllArchitectures = <ThrowOnError extends boolean = false>(
    options: Options<ArchitectureApiGetAllArchitecturesData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ArchitectureApiGetAllArchitecturesResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/architecture/{id}/{name}",
    });
};

/**
 * Get Result
 */
export const resultApiGetResult = <ThrowOnError extends boolean = false>(
    options: Options<ResultApiGetResultData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ResultApiGetResultResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/result/{id}",
    });
};

/**
 * Get Domains
 */
export const resultApiGetDomains = <ThrowOnError extends boolean = false>(
    options: Options<ResultApiGetDomainsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ResultApiGetDomainsResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/result/{id}/domains",
    });
};

/**
 * Search
 */
export const searchApiSearch = <ThrowOnError extends boolean = false>(
    options: Options<SearchApiSearchData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<SearchApiSearchResponse, unknown, ThrowOnError>({
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options?.headers,
        },
        url: "/api/v1/search/{algo}",
    });
};

/**
 * Get Jobs
 */
export const searchApiGetJobs = <ThrowOnError extends boolean = false>(
    options?: Options<SearchApiGetJobsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<SearchApiGetJobsResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/search",
    });
};

/**
 * Get
 */
export const taxonomyApiGet = <ThrowOnError extends boolean = false>(
    options?: Options<TaxonomyApiGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/taxonomy",
    });
};

/**
 * Search Taxonomy
 */
export const taxonomyApiSearchTaxonomy = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiSearchTaxonomyData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<TaxonomyApiSearchTaxonomyResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/taxonomy/search",
    });
};

/**
 * Get Taxonomy
 */
export const taxonomyApiGetTaxonomy = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<TaxonomyApiGetTaxonomyResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/taxonomy/{id}",
    });
};

/**
 * Get Taxonomy Tree
 */
export const taxonomyApiGetTaxonomyTree = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyTreeData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<TaxonomyApiGetTaxonomyTreeResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/taxonomy/{id}/tree",
    });
};

/**
 * Get Taxonomy Distribution
 */
export const taxonomyApiGetTaxonomyDistribution = <ThrowOnError extends boolean = false>(
    options: Options<TaxonomyApiGetTaxonomyDistributionData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<TaxonomyApiGetTaxonomyDistributionResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/taxonomy/{id}/distribution",
    });
};

/**
 * Download File
 */
export const downloadApiDownloadFile = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiDownloadFileData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/download/{id}/{format}",
    });
};

/**
 * Generate File
 */
export const downloadApiGenerateFile = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiGenerateFileData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<DownloadApiGenerateFileResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/download/{id}/{format}",
    });
};

/**
 * Get Downloads
 */
export const downloadApiGetDownloads = <ThrowOnError extends boolean = false>(
    options: Options<DownloadApiGetDownloadsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<DownloadApiGetDownloadsResponse, unknown, ThrowOnError>({
        ...options,
        url: "/api/v1/download/{id}",
    });
};
