// This file is auto-generated by @hey-api/openapi-ts

import type { SearchApiGetJobsResponse, TaxonomyApiGetTaxonomyTreeResponse } from "./types.gen";

const taskResultSchemaSchemaResponseTransformer = (data: any) => {
    data.date_created = new Date(data.date_created);
    data.date_done = new Date(data.date_done);
    return data;
};

const jobsResponseSchemaSchemaResponseTransformer = (data: any) => {
    data.task = taskResultSchemaSchemaResponseTransformer(data.task);
    return data;
};

export const searchApiGetJobsResponseTransformer = async (data: any): Promise<SearchApiGetJobsResponse> => {
    data = data.map((item: any) => {
        return jobsResponseSchemaSchemaResponseTransformer(item);
    });
    return data;
};

const taxonomyTreeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => {
        return taxonomyTreeSchemaResponseTransformer(item);
    });
    return data;
};

const taxonomyTreeResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.tree) {
        data.tree = taxonomyTreeSchemaResponseTransformer(data.tree);
    }
    return data;
};

export const taxonomyApiGetTaxonomyTreeResponseTransformer = async (
    data: any,
): Promise<TaxonomyApiGetTaxonomyTreeResponse> => {
    data = taxonomyTreeResponseSchemaSchemaResponseTransformer(data);
    return data;
};
