// This file is auto-generated by @hey-api/openapi-ts

import type {
    SearchApiGetDatabasesResponse,
    SearchApiGetJobDetailsResponse,
    SearchApiGetJobsResponse,
    TaxonomyApiGetTaxonomyTreeResponse,
} from "./types.gen";

const databaseResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.release_date) {
        data.release_date = new Date(data.release_date);
    }
    return data;
};

export const searchApiGetDatabasesResponseTransformer = async (data: any): Promise<SearchApiGetDatabasesResponse> => {
    data = data.map((item: any) => databaseResponseSchemaSchemaResponseTransformer(item));
    return data;
};

const taskResultSchemaSchemaResponseTransformer = (data: any) => {
    data.date_created = new Date(data.date_created);
    data.date_done = new Date(data.date_done);
    return data;
};

const jobDetailsResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.task) {
        data.task = taskResultSchemaSchemaResponseTransformer(data.task);
    }
    if (data.task) {
        data.task = taskResultSchemaSchemaResponseTransformer(data.task);
    }
    data.database = databaseResponseSchemaSchemaResponseTransformer(data.database);
    if (data.date_submitted) {
        data.date_submitted = new Date(data.date_submitted);
    }
    return data;
};

export const searchApiGetJobDetailsResponseTransformer = async (data: any): Promise<SearchApiGetJobDetailsResponse> => {
    data = jobDetailsResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const jobsResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.task) {
        data.task = taskResultSchemaSchemaResponseTransformer(data.task);
    }
    if (data.task) {
        data.task = taskResultSchemaSchemaResponseTransformer(data.task);
    }
    if (data.date_submitted) {
        data.date_submitted = new Date(data.date_submitted);
    }
    return data;
};

export const searchApiGetJobsResponseTransformer = async (data: any): Promise<SearchApiGetJobsResponse> => {
    data = data.map((item: any) => jobsResponseSchemaSchemaResponseTransformer(item));
    return data;
};

const taxonomyTreeSchemaResponseTransformer = (data: any) => {
    if (data.children) {
        data.children = data.children.map((item: any) => taxonomyTreeSchemaResponseTransformer(item));
    }
    return data;
};

const taxonomyTreeResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.tree) {
        data.tree = taxonomyTreeSchemaResponseTransformer(data.tree);
    }
    return data;
};

export const taxonomyApiGetTaxonomyTreeResponseTransformer = async (
    data: any,
): Promise<TaxonomyApiGetTaxonomyTreeResponse> => {
    data = taxonomyTreeResponseSchemaSchemaResponseTransformer(data);
    return data;
};
