// This file is auto-generated by @hey-api/openapi-ts

/**
 * ArchitectureSchema
 */
export type ArchitectureSchema = {
    /**
     * Sequence Accession
     */
    sequence_accession?: string | null;
    /**
     * Sequence External Link
     */
    sequence_external_link?: string | null;
    /**
     * Names
     */
    names: string;
    /**
     * Score
     */
    score: number;
    /**
     * Graphics
     */
    graphics: {
        [key: string]: unknown;
    };
    /**
     * Accessions
     */
    accessions: string;
};

/**
 * ArchitectureQuerySchema
 */
export type ArchitectureQuerySchema = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * ArchitectureAggregationSchema
 */
export type ArchitectureAggregationSchema = {
    /**
     * Count
     */
    count: number;
    architecture: ArchitectureSchema;
};

/**
 * ArchitectureResponseSchema
 */
export type ArchitectureResponseSchema = {
    /**
     * Status
     */
    status: string;
    /**
     * Architectures
     */
    architectures?: Array<ArchitectureAggregationSchema> | null;
    /**
     * Page Count
     */
    page_count?: number | null;
};

/**
 * Annotation
 */
export type Annotation = {
    /**
     * Length
     */
    length: number;
    /**
     * Regions
     */
    regions: Array<Region>;
};

/**
 * ArchitectureAnnotationsResponseSchema
 */
export type ArchitectureAnnotationsResponseSchema = {
    /**
     * Status
     */
    status: string;
    /**
     * Annotations
     */
    annotations?: Array<Annotation> | null;
};

/**
 * Region
 */
export type Region = {
    /**
     * Color
     */
    color?: string;
    /**
     * End Style
     */
    end_style?: string;
    /**
     * Start Style
     */
    start_style?: string;
    /**
     * Display
     */
    display?: boolean;
    /**
     * Href
     */
    href?: string;
    /**
     * Clan
     */
    clan?: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Type
     */
    type?: string;
    /**
     * Text
     */
    text: string;
    /**
     * Model Length
     */
    model_length: number;
    /**
     * Model Start
     */
    model_start: number;
    /**
     * Model End
     */
    model_end: number;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Ali Start
     */
    ali_start: number;
    /**
     * Ali End
     */
    ali_end: number;
};

/**
 * ArchitectureListResponseSchema
 */
export type ArchitectureListResponseSchema = {
    /**
     * Status
     */
    status: string;
    /**
     * Architectures
     */
    architectures: Array<ArchitectureSchema> | null;
    /**
     * Page Count
     */
    page_count?: number | null;
};

/**
 * ResultQuerySchema
 */
export type ResultQuerySchema = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Taxonomy Ids
     */
    taxonomy_ids?: Array<number> | null;
    /**
     * Architecture
     */
    architecture?: string | null;
    /**
     * With Domains
     */
    with_domains?: boolean | null;
};

/**
 * BatchResponseSchema
 */
export type BatchResponseSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Query Name
     */
    query_name: string;
    /**
     * Status
     */
    status: string;
};

/**
 * HmmdSearchStats
 */
export type HmmdSearchStats = {
    /**
     * Id
     */
    id?: string;
    /**
     * Algo
     */
    algo?: string;
    /**
     * Database
     */
    database?: string;
    /**
     * Elapsed
     */
    elapsed: number;
    /**
     * User
     */
    user: number;
    /**
     * Sys
     */
    sys: number;
    /**
     * Z
     */
    Z: number;
    /**
     * Domz
     */
    domZ: number;
    /**
     * Z Setby
     */
    Z_setby: number;
    /**
     * Domz Setby
     */
    domZ_setby: number;
    /**
     * Nmodels
     */
    nmodels: number;
    /**
     * Nseqs
     */
    nseqs: number;
    /**
     * N Past Msv
     */
    n_past_msv: number;
    /**
     * N Past Bias
     */
    n_past_bias: number;
    /**
     * N Past Vit
     */
    n_past_vit: number;
    /**
     * N Past Fwd
     */
    n_past_fwd: number;
    /**
     * Nhits
     */
    nhits: number;
    /**
     * Nreported
     */
    nreported: number;
    /**
     * Nincluded
     */
    nincluded: number;
    /**
     * Ngained
     */
    ngained?: number | null;
    /**
     * Nlost
     */
    nlost?: number | null;
    /**
     * Ndropped
     */
    ndropped?: number | null;
    /**
     * First Gained Index
     */
    first_gained_index?: number | null;
    /**
     * Hit Offsets
     */
    hit_offsets: Array<number> | null;
    /**
     * Size
     */
    size?: number;
};

/**
 * JackhmmerResponseSchema
 */
export type JackhmmerResponseSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Iteration
     */
    iteration: number;
    /**
     * Convergence Stats
     */
    convergence_stats: {
        [key: string]: number;
    } | null;
};

/**
 * P7AlignmentDisplay
 */
export type P7AlignmentDisplay = {
    /**
     * Size
     */
    size: number;
    /**
     * N
     */
    n: number;
    /**
     * Hmmfrom
     */
    hmmfrom: number;
    /**
     * Hmmto
     */
    hmmto: number;
    /**
     * M
     */
    m: number;
    /**
     * Sqfrom
     */
    sqfrom: number;
    /**
     * Sqto
     */
    sqto: number;
    /**
     * L
     */
    l: number;
    /**
     * String Presence Flags
     */
    string_presence_flags: unknown;
    /**
     * Rfline
     */
    rfline: string | null;
    /**
     * Mmline
     */
    mmline: string | null;
    /**
     * Csline
     */
    csline: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Mline
     */
    mline: string;
    /**
     * Aseq
     */
    aseq: string | null;
    /**
     * Ntseq
     */
    ntseq: string | null;
    /**
     * Ppline
     */
    ppline: string | null;
    /**
     * Hmmname
     */
    hmmname: string;
    /**
     * Hmmacc
     */
    hmmacc: string;
    /**
     * Hmmdesc
     */
    hmmdesc: string;
    /**
     * Sqname
     */
    sqname: string;
    /**
     * Sqacc
     */
    sqacc: string;
    /**
     * Sqdesc
     */
    sqdesc: string;
    /**
     * Identity
     */
    identity?: [number, number] | null;
    /**
     * Similarity
     */
    similarity?: [number, number] | null;
};

/**
 * P7Domain
 */
export type P7Domain = {
    /**
     * Size
     */
    size: number;
    /**
     * Ienv
     */
    ienv: number;
    /**
     * Jenv
     */
    jenv: number;
    /**
     * Iali
     */
    iali: number;
    /**
     * Jali
     */
    jali: number;
    /**
     * Iorf
     */
    iorf: number;
    /**
     * Jorf
     */
    jorf: number;
    /**
     * Envsc
     */
    envsc: number;
    /**
     * Domcorrection
     */
    domcorrection: number;
    /**
     * Dombias
     */
    dombias: number;
    /**
     * Oasc
     */
    oasc: number;
    /**
     * Bitscore
     */
    bitscore: number;
    /**
     * Lnp
     */
    lnP: number;
    /**
     * Ievalue
     */
    ievalue?: number;
    /**
     * Cevalue
     */
    cevalue?: number;
    /**
     * Is Reported
     */
    is_reported: boolean;
    /**
     * Is Included
     */
    is_included: boolean;
    /**
     * Scores Per Pos Length
     */
    scores_per_pos_length: number;
    /**
     * Scores Per Pos
     */
    scores_per_pos: Array<number>;
    alignment_display: P7AlignmentDisplay;
    /**
     * Display
     */
    display?: boolean;
    /**
     * Outcompeted
     */
    outcompeted?: boolean;
    /**
     * Significant
     */
    significant?: boolean;
    /**
     * Uniq
     */
    uniq?: number;
    /**
     * Segments
     */
    segments?: Array<[number, number]> | null;
    /**
     * Predicted Active Sites
     */
    predicted_active_sites?: Array<[string, Array<number>]> | null;
};

/**
 * P7Hit
 */
export type P7Hit = {
    /**
     * Index
     */
    index?: number;
    /**
     * Size
     */
    size: number;
    /**
     * Window Length
     */
    window_length: number;
    /**
     * Sortkey
     */
    sortkey: number;
    /**
     * Score
     */
    score: number;
    /**
     * Pre Score
     */
    pre_score: number;
    /**
     * Sum Score
     */
    sum_score: number;
    /**
     * Bias
     */
    bias?: number;
    /**
     * Lnp
     */
    lnP: number;
    /**
     * Pre Lnp
     */
    pre_lnP: number;
    /**
     * Sum Lnp
     */
    sum_lnP: number;
    /**
     * Nexpected
     */
    nexpected: number;
    /**
     * Nregions
     */
    nregions: number;
    /**
     * Nclustered
     */
    nclustered: number;
    /**
     * Noverlaps
     */
    noverlaps: number;
    /**
     * Nenvelopes
     */
    nenvelopes: number;
    /**
     * Ndom
     */
    ndom: number;
    /**
     * Flags
     */
    flags: unknown;
    /**
     * Is Reported
     */
    is_reported?: boolean;
    /**
     * Is Included
     */
    is_included?: boolean;
    /**
     * Is New
     */
    is_new?: boolean;
    /**
     * Is Dropped
     */
    is_dropped?: boolean;
    /**
     * Nreported
     */
    nreported: number;
    /**
     * Nincluded
     */
    nincluded: number;
    /**
     * Best Domain
     */
    best_domain: number;
    /**
     * Seqidx
     */
    seqidx: number;
    /**
     * Subseq Start
     */
    subseq_start: number;
    /**
     * String Presence Flags
     */
    string_presence_flags: unknown;
    /**
     * Name
     */
    name: string;
    /**
     * Acc
     */
    acc: string | null;
    /**
     * Desc
     */
    desc: string | null;
    /**
     * Evalue
     */
    evalue?: number;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Domains
     */
    domains: Array<P7Domain> | null;
};

/**
 * Result
 */
export type Result = {
    stats: HmmdSearchStats;
    /**
     * Hits
     */
    hits: Array<P7Hit>;
};

/**
 * ResultResponseSchema
 */
export type ResultResponseSchema = {
    /**
     * Status
     */
    status: string;
    result?: Result | null;
    /**
     * Page Count
     */
    page_count?: number | null;
};

/**
 * AlignmentQuerySchema
 */
export type AlignmentQuerySchema = {
    /**
     * Index
     */
    index?: number;
};

/**
 * AlignmentResponseSchema
 */
export type AlignmentResponseSchema = {
    /**
     * Status
     */
    status: string;
    /**
     * Domains
     */
    domains: Array<P7Domain> | null;
};

/**
 * DatabaseResponseSchema
 */
export type DatabaseResponseSchema = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Type
     */
    type?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Release Date
     */
    release_date?: Date;
    /**
     * Order
     */
    order?: number;
};

/**
 * JobDetailsResponseSchema
 */
export type JobDetailsResponseSchema = {
    task: TaskResultSchema | null;
    database: DatabaseResponseSchema;
    /**
     * Iteration
     */
    iteration: number | null;
    /**
     * Next Job Id
     */
    next_job_id: string | null;
    /**
     * Previous Job Id
     */
    previous_job_id: string | null;
    /**
     * Parent Job Id
     */
    parent_job_id: string | null;
    /**
     * Include
     */
    include: Array<number>;
    /**
     * Exclude
     */
    exclude: Array<number>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Algo
     */
    algo?: string;
    /**
     * Input
     */
    input?: string | null;
    /**
     * Input Type
     */
    input_type?: string;
    /**
     * Calculated Input
     */
    calculated_input?: string | null;
    /**
     * Threshold
     */
    threshold?: string;
    /**
     * E
     */
    E?: number | null;
    /**
     * domE
     */
    domE?: number | null;
    /**
     * T
     */
    T?: number | null;
    /**
     * domT
     */
    domT?: number | null;
    /**
     * incE
     */
    incE?: number | null;
    /**
     * incdomE
     */
    incdomE?: number | null;
    /**
     * incT
     */
    incT?: number | null;
    /**
     * incdomT
     */
    incdomT?: number | null;
    /**
     * Taxonomy Ids
     */
    taxonomy_ids?: {
        [key: string]: unknown;
    };
    /**
     * Popen
     */
    popen?: number | null;
    /**
     * Pextend
     */
    pextend?: number | null;
    /**
     * Mx
     */
    mx?: string | null;
    /**
     * Exclude All
     */
    exclude_all?: boolean;
    /**
     * Iterations
     */
    iterations?: number | null;
    /**
     * Date Submitted
     */
    date_submitted?: Date | null;
    /**
     * Number Of Hits
     */
    number_of_hits?: number | null;
    /**
     * Number Of Included
     */
    number_of_included?: number | null;
    /**
     * Number Of Gained
     */
    number_of_gained?: number | null;
    /**
     * Number Of Dropped
     */
    number_of_dropped?: number | null;
    /**
     * Number Of Lost
     */
    number_of_lost?: number | null;
    /**
     * First Gained Index
     */
    first_gained_index?: number | null;
    /**
     * Email Address
     */
    email_address?: string | null;
};

/**
 * TaskResultSchema
 */
export type TaskResultSchema = {
    /**
     * Task State
     * Current state of the task being run
     */
    status?: string;
    /**
     * Created DateTime
     * Datetime field when the task result was created in UTC
     */
    date_created: Date;
    /**
     * Completed DateTime
     * Datetime field when the task was completed in UTC
     */
    date_done: Date;
};

/**
 * ValidationErrorDetailSchema
 */
export type ValidationErrorDetailSchema = {
    /**
     * Type
     */
    type: string;
    /**
     * Loc
     */
    loc: Array<string>;
    /**
     * Msg
     */
    msg: string;
};

/**
 * ValidationErrorSchema
 */
export type ValidationErrorSchema = {
    /**
     * Detail
     */
    detail: Array<ValidationErrorDetailSchema>;
};

/**
 * SearchPatchSchema
 */
export type SearchPatchSchema = {
    /**
     * Email Address
     */
    email_address?: string | null;
};

/**
 * AlgoChoices
 */
export const AlgoChoices = {
    PHMMER: "phmmer",
    HMMSEARCH: "hmmsearch",
    HMMSCAN: "hmmscan",
    JACKHMMER: "jackhmmer",
} as const;

/**
 * AlgoChoices
 */
export type AlgoChoices = (typeof AlgoChoices)[keyof typeof AlgoChoices];

/**
 * SearchResponseSchema
 */
export type SearchResponseSchema = {
    /**
     * Id
     */
    id: string;
};

/**
 * SearchRequestSchema
 */
export type SearchRequestSchema = {
    /**
     * Input
     */
    input: string;
    /**
     * Input Type
     */
    input_type?: string | null;
    /**
     * Database
     */
    database?: string | null;
    /**
     * Taxonomy Ids
     */
    taxonomy_ids?: Array<number> | null;
    /**
     * Include
     */
    include?: Array<number> | null;
    /**
     * Exclude
     */
    exclude?: Array<number> | null;
    /**
     * Threshold
     */
    threshold?: string | null;
    /**
     * E
     */
    E?: number | null;
    /**
     * domE
     */
    domE?: number | null;
    /**
     * T
     */
    T?: number | null;
    /**
     * domT
     */
    domT?: number | null;
    /**
     * incE
     */
    incE?: number | null;
    /**
     * incdomE
     */
    incdomE?: number | null;
    /**
     * incT
     */
    incT?: number | null;
    /**
     * incdomT
     */
    incdomT?: number | null;
    /**
     * Popen
     */
    popen?: number | null;
    /**
     * Pextend
     */
    pextend?: number | null;
    /**
     * Mx
     */
    mx?: string | null;
    /**
     * With Taxonomy
     */
    with_taxonomy?: boolean | null;
    /**
     * With Architecture
     */
    with_architecture?: boolean | null;
    /**
     * Iterations
     */
    iterations?: number | null;
    /**
     * Exclude All
     */
    exclude_all?: boolean | null;
    /**
     * Email Address
     */
    email_address?: string | null;
};

/**
 * JobsResponseSchema
 */
export type JobsResponseSchema = {
    task: TaskResultSchema | null;
    /**
     * Query Name
     */
    query_name: string;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Algo
     */
    algo?: string;
    /**
     * Date Submitted
     */
    date_submitted?: Date | null;
};

/**
 * TaxonomyResponseSchema
 */
export type TaxonomyResponseSchema = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Rank
     */
    rank: string;
};

/**
 * TaxonomyTree
 */
export type TaxonomyTree = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Hitcount
     */
    hitcount: number | null;
    /**
     * Hitdist
     */
    hitdist: Array<number> | null;
    /**
     * Children
     */
    children: Array<TaxonomyTree> | null;
};

/**
 * TaxonomyTreeResponseSchema
 */
export type TaxonomyTreeResponseSchema = {
    /**
     * Status
     */
    status: string;
    tree?: TaxonomyTree | null;
};

/**
 * TaxonomyDistributionGraph
 */
export type TaxonomyDistributionGraph = {
    /**
     * Data
     */
    data: Array<Array<number>>;
    /**
     * Labels
     */
    labels: Array<string>;
    /**
     * Categories
     */
    categories: Array<string>;
    /**
     * Colors
     */
    colors: Array<string>;
};

/**
 * TaxonomyDistributionResponseSchema
 */
export type TaxonomyDistributionResponseSchema = {
    /**
     * Status
     */
    status: string;
    graph?: TaxonomyDistributionGraph | null;
};

/**
 * DownloadsQuerySchema
 */
export type DownloadsQuerySchema = {
    /**
     * Taxonomy Ids
     */
    taxonomy_ids?: Array<number>;
    /**
     * Architecture
     */
    architecture?: string;
};

/**
 * DownloadsResponseSchema
 */
export type DownloadsResponseSchema = {
    /**
     * Format
     */
    format: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Status
     */
    status: string;
    /**
     * Url
     */
    url: string | null;
    /**
     * Size
     */
    size: number | null;
};

export type ArchitectureApiGetArchitectureNameData = {
    body?: never;
    path: {
        /**
         * Accessions
         */
        accessions: string;
    };
    query?: never;
    url: "/api/v1/architecture/name/{accessions}";
};

export type ArchitectureApiGetArchitectureNameResponses = {
    /**
     * OK
     */
    200: ArchitectureSchema;
};

export type ArchitectureApiGetArchitectureNameResponse =
    ArchitectureApiGetArchitectureNameResponses[keyof ArchitectureApiGetArchitectureNameResponses];

export type ArchitectureApiGetDomainArchitecturesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: "/api/v1/architecture/{id}";
};

export type ArchitectureApiGetDomainArchitecturesResponses = {
    /**
     * OK
     */
    200: ArchitectureResponseSchema;
};

export type ArchitectureApiGetDomainArchitecturesResponse =
    ArchitectureApiGetDomainArchitecturesResponses[keyof ArchitectureApiGetDomainArchitecturesResponses];

export type ArchitectureApiGetAnnotationsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/architecture/{id}/annotations";
};

export type ArchitectureApiGetAnnotationsResponses = {
    /**
     * OK
     */
    200: ArchitectureAnnotationsResponseSchema;
};

export type ArchitectureApiGetAnnotationsResponse =
    ArchitectureApiGetAnnotationsResponses[keyof ArchitectureApiGetAnnotationsResponses];

export type ArchitectureApiGetAllArchitecturesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Accessions
         */
        accessions: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: "/api/v1/architecture/{id}/{accessions}";
};

export type ArchitectureApiGetAllArchitecturesResponses = {
    /**
     * OK
     */
    200: ArchitectureListResponseSchema;
};

export type ArchitectureApiGetAllArchitecturesResponse =
    ArchitectureApiGetAllArchitecturesResponses[keyof ArchitectureApiGetAllArchitecturesResponses];

export type ResultApiGetResultData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Taxonomy Ids
         */
        taxonomy_ids?: Array<number> | null;
        /**
         * Architecture
         */
        architecture?: string | null;
        /**
         * With Domains
         */
        with_domains?: boolean | null;
    };
    url: "/api/v1/result/{id}";
};

export type ResultApiGetResultResponses = {
    /**
     * Response
     * OK
     */
    200: ResultResponseSchema | Array<JackhmmerResponseSchema> | Array<BatchResponseSchema>;
};

export type ResultApiGetResultResponse = ResultApiGetResultResponses[keyof ResultApiGetResultResponses];

export type ResultApiGetDomainsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Index
         */
        index?: number;
    };
    url: "/api/v1/result/{id}/domains";
};

export type ResultApiGetDomainsResponses = {
    /**
     * OK
     */
    200: AlignmentResponseSchema;
};

export type ResultApiGetDomainsResponse = ResultApiGetDomainsResponses[keyof ResultApiGetDomainsResponses];

export type SearchApiGetDatabasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/search/databases";
};

export type SearchApiGetDatabasesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<DatabaseResponseSchema>;
};

export type SearchApiGetDatabasesResponse = SearchApiGetDatabasesResponses[keyof SearchApiGetDatabasesResponses];

export type SearchApiGetJobDetailsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/search/{id}";
};

export type SearchApiGetJobDetailsResponses = {
    /**
     * OK
     */
    200: JobDetailsResponseSchema;
};

export type SearchApiGetJobDetailsResponse = SearchApiGetJobDetailsResponses[keyof SearchApiGetJobDetailsResponses];

export type SearchApiUpdateSearchData = {
    body: SearchPatchSchema;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/search/{id}";
};

export type SearchApiUpdateSearchErrors = {
    /**
     * Unprocessable Content
     */
    422: ValidationErrorSchema;
};

export type SearchApiUpdateSearchError = SearchApiUpdateSearchErrors[keyof SearchApiUpdateSearchErrors];

export type SearchApiUpdateSearchResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SearchApiUpdateSearchResponse = SearchApiUpdateSearchResponses[keyof SearchApiUpdateSearchResponses];

export type SearchApiGetJobQueryData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/search/{id}/query";
};

export type SearchApiGetJobQueryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SearchApiSearchData = {
    body: SearchRequestSchema;
    path: {
        /**
         * AlgoChoices
         */
        algo: "phmmer" | "hmmsearch" | "hmmscan" | "jackhmmer";
    };
    query?: never;
    url: "/api/v1/search/{algo}";
};

export type SearchApiSearchErrors = {
    /**
     * Unprocessable Content
     */
    422: ValidationErrorSchema;
};

export type SearchApiSearchError = SearchApiSearchErrors[keyof SearchApiSearchErrors];

export type SearchApiSearchResponses = {
    /**
     * OK
     */
    200: SearchResponseSchema;
};

export type SearchApiSearchResponse = SearchApiSearchResponses[keyof SearchApiSearchResponses];

export type SearchApiGetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/search";
};

export type SearchApiGetJobsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<JobsResponseSchema>;
};

export type SearchApiGetJobsResponse = SearchApiGetJobsResponses[keyof SearchApiGetJobsResponses];

export type TaxonomyApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/taxonomy";
};

export type TaxonomyApiGetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TaxonomyApiSearchTaxonomyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Database
         */
        database: string;
    };
    url: "/api/v1/taxonomy/search";
};

export type TaxonomyApiSearchTaxonomyResponses = {
    /**
     * Response
     * OK
     */
    200: Array<TaxonomyResponseSchema>;
};

export type TaxonomyApiSearchTaxonomyResponse =
    TaxonomyApiSearchTaxonomyResponses[keyof TaxonomyApiSearchTaxonomyResponses];

export type TaxonomyApiGetTaxonomyData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: "/api/v1/taxonomy/{id}";
};

export type TaxonomyApiGetTaxonomyResponses = {
    /**
     * OK
     */
    200: TaxonomyResponseSchema;
};

export type TaxonomyApiGetTaxonomyResponse = TaxonomyApiGetTaxonomyResponses[keyof TaxonomyApiGetTaxonomyResponses];

export type TaxonomyApiGetTaxonomyTreeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/taxonomy/{id}/tree";
};

export type TaxonomyApiGetTaxonomyTreeResponses = {
    /**
     * OK
     */
    200: TaxonomyTreeResponseSchema;
};

export type TaxonomyApiGetTaxonomyTreeResponse =
    TaxonomyApiGetTaxonomyTreeResponses[keyof TaxonomyApiGetTaxonomyTreeResponses];

export type TaxonomyApiGetTaxonomyDistributionData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: "/api/v1/taxonomy/{id}/distribution";
};

export type TaxonomyApiGetTaxonomyDistributionResponses = {
    /**
     * OK
     */
    200: TaxonomyDistributionResponseSchema;
};

export type TaxonomyApiGetTaxonomyDistributionResponse =
    TaxonomyApiGetTaxonomyDistributionResponses[keyof TaxonomyApiGetTaxonomyDistributionResponses];

export type DownloadApiDownloadFileData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Format
         */
        format: string;
    };
    query?: {
        /**
         * Taxonomy Ids
         */
        taxonomy_ids?: Array<number>;
        /**
         * Architecture
         */
        architecture?: string;
    };
    url: "/api/v1/download/{id}/{format}";
};

export type DownloadApiDownloadFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DownloadApiGenerateFileData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Format
         */
        format: string;
    };
    query?: {
        /**
         * Taxonomy Ids
         */
        taxonomy_ids?: Array<number>;
        /**
         * Architecture
         */
        architecture?: string;
    };
    url: "/api/v1/download/{id}/{format}";
};

export type DownloadApiGenerateFileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DownloadApiGenerateFileResponse = DownloadApiGenerateFileResponses[keyof DownloadApiGenerateFileResponses];

export type DownloadApiGetDownloadsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Taxonomy Ids
         */
        taxonomy_ids?: Array<number>;
        /**
         * Architecture
         */
        architecture?: string;
    };
    url: "/api/v1/download/{id}";
};

export type DownloadApiGetDownloadsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<DownloadsResponseSchema>;
};

export type DownloadApiGetDownloadsResponse = DownloadApiGetDownloadsResponses[keyof DownloadApiGetDownloadsResponses];

export type ClientOptions = {
    baseUrl: string;
};
