// This file is auto-generated by @hey-api/openapi-ts

export type HmmerJobStatusSchema = {
  /**
   * The id of the job
   */
  id: string;
  /**
   * The status of the job
   */
  status: string;
  /**
   * URL to get the result of the job
   */
  result_url: string | null;
  /**
   * The error message of the job
   */
  error_message: string | null;
};

export type HmmerJobCreatedSchema = {
  /**
   * The id of the job
   */
  id: string;
  /**
   * The status of the job
   */
  status: string;
  /**
   * URL to get the status of the job
   */
  status_url: string;
};

export type PhmmerJobSchema = {
  popen?: number | null;
  pextend?: number | null;
  mx?:
    | ("BLOSUM62" | "BLOSUM45" | "BLOSUM90" | "PAM30" | "PAM70" | "PAM250")
    | null;
  threshold?: "evalue" | "bitscore";
  incE?: number | null;
  incdomE?: number | null;
  E?: number | null;
  domE?: number | null;
  incT?: number | null;
  incdomT?: number | null;
  T?: number | null;
  domT?: number | null;
  seq: string;
  seqdb: string;
};

export type QuerySchema = {
  limit?: number;
  offset?: number;
};

export type Alignment = {
  hmm_accession: string;
  hmm_from: number;
  hmm_length: number;
  hmm_name: string;
  hmm_sequence: string;
  hmm_to: number;
  identity_sequence: string;
  target_from: number;
  target_length: number;
  target_name: string;
  target_sequence: string;
  target_to: number;
};

export type Domain = {
  alignment: Alignment;
  bias: number;
  c_evalue: number;
  correction: number;
  env_from: number;
  env_to: number;
  envelope_score: number;
  i_evalue: number;
  included: boolean;
  pvalue: number;
  reported: boolean;
  score: number;
};

export type Domains = {
  included: Array<Domain>;
  reported: Array<Domain>;
};

export type Hit = {
  bias: number;
  domains: Domains;
  dropped: boolean;
  duplicate: boolean;
  evalue: number;
  included: boolean;
  length: number;
  name: string;
  new: boolean;
  pre_score: number;
  pvalue: number;
  reported: boolean;
  score: number;
  sum_score: number;
  metadata: Metadata;
};

export type Metadata = {
  structures?: Array<Structure>;
  taxonomy_id: number;
  architecture_checksum: number;
  architecture_score: number;
  architecture: string;
  accession: string;
  identifier: string;
  description: string;
  uniprot_accession: string | null;
  uniprot_identifier: string | null;
  kingdom: string | null;
  phylum: string | null;
  species: string | null;
  external_link: string;
  taxonomy_link: string;
};

export type Result = {
  hits: Array<Hit>;
  stats: Stats;
};

export type Stats = {
  E: number;
  T: number | null;
  Z: number;
  bit_cutoffs: string | null;
  domE: number;
  domT: number | null;
  domZ: number;
  incE: number;
  incT: number | null;
  incdomE: number;
  incdomT: number | null;
  searched_models: number;
  searched_nodes: number;
  searched_residues: number;
  searched_sequences: number;
  included_hits: number;
  reported_hits: number;
};

export type Structure = {
  id: string;
  external_link: string;
};

export type MessageSchema = {
  message: string;
};

export type SearchApiStatusData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/v1/search/{id}";
};

export type SearchApiStatusResponses = {
  /**
   * OK
   */
  200: HmmerJobStatusSchema;
};

export type SearchApiStatusResponse =
  SearchApiStatusResponses[keyof SearchApiStatusResponses];

export type PhmmerApiSearchData = {
  body: PhmmerJobSchema;
  path?: never;
  query?: never;
  url: "/api/v1/search/phmmer";
};

export type PhmmerApiSearchResponses = {
  /**
   * Accepted
   */
  202: HmmerJobCreatedSchema;
};

export type PhmmerApiSearchResponse =
  PhmmerApiSearchResponses[keyof PhmmerApiSearchResponses];

export type ResultApiGetResultData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/api/v1/result/{id}";
};

export type ResultApiGetResultErrors = {
  /**
   * Not Found
   */
  404: MessageSchema;
  /**
   * Conflict
   */
  409: MessageSchema;
  /**
   * Gone
   */
  410: MessageSchema;
};

export type ResultApiGetResultError =
  ResultApiGetResultErrors[keyof ResultApiGetResultErrors];

export type ResultApiGetResultResponses = {
  /**
   * OK
   */
  200: Result;
};

export type ResultApiGetResultResponse =
  ResultApiGetResultResponses[keyof ResultApiGetResultResponses];

export type TaxonomyApiGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/taxonomy";
};

export type TaxonomyApiGetResponses = {
  /**
   * OK
   */
  200: unknown;
};
