// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zArchitectureSchema = z.object({
    sequence_accession: z.union([z.string(), z.null()]).optional(),
    sequence_external_link: z.union([z.string(), z.null()]).optional(),
    names: z.string(),
    score: z.number(),
    graphics: z.object({}),
    accessions: z.string(),
});

export const zArchitectureQuerySchema = z.object({
    page: z.number().optional().default(1),
    page_size: z.number().optional().default(50),
});

export const zArchitectureAggregationSchema = z.object({
    count: z.number(),
    architecture: zArchitectureSchema,
});

export const zArchitectureResponseSchema = z.object({
    status: z.string(),
    architectures: z.union([z.array(zArchitectureAggregationSchema), z.null()]).optional(),
    page_count: z.union([z.number(), z.null()]).optional(),
});

export const zAnnotation = z.object({
    length: z.number(),
    regions: z.array(
        z.object({
            color: z.string().optional().default(""),
            end_style: z.string().optional().default("curved"),
            start_style: z.string().optional().default("curved"),
            display: z.boolean().optional().default(true),
            href: z.string().optional().default(""),
            clan: z.string().optional().default(""),
            metadata: z.object({}).optional().default({}),
            type: z.string().optional().default("pfam"),
            text: z.string(),
            model_length: z.number(),
            model_start: z.number(),
            model_end: z.number(),
            start: z.number(),
            end: z.number(),
            ali_start: z.number(),
            ali_end: z.number(),
        }),
    ),
});

export const zArchitectureAnnotationsResponseSchema = z.object({
    status: z.string(),
    annotations: z.union([z.array(zAnnotation), z.null()]).optional(),
});

export const zRegion = z.object({
    color: z.string().optional().default(""),
    end_style: z.string().optional().default("curved"),
    start_style: z.string().optional().default("curved"),
    display: z.boolean().optional().default(true),
    href: z.string().optional().default(""),
    clan: z.string().optional().default(""),
    metadata: z.object({}).optional().default({}),
    type: z.string().optional().default("pfam"),
    text: z.string(),
    model_length: z.number(),
    model_start: z.number(),
    model_end: z.number(),
    start: z.number(),
    end: z.number(),
    ali_start: z.number(),
    ali_end: z.number(),
});

export const zArchitectureListResponseSchema = z.object({
    status: z.string(),
    architectures: z.union([z.array(zArchitectureSchema), z.null()]),
    page_count: z.union([z.number(), z.null()]).optional(),
});

export const zResultQuerySchema = z.object({
    page: z.number().optional().default(1),
    page_size: z.number().optional().default(50),
    taxonomy_ids: z.union([z.array(z.number()), z.null()]).optional(),
    architecture: z.union([z.string(), z.null()]).optional(),
    with_domains: z.union([z.boolean(), z.null()]).optional(),
});

export const zHmmdSearchStats = z.object({
    id: z.string().optional(),
    algo: z.string().optional(),
    database: z.string().optional(),
    elapsed: z.number(),
    user: z.number(),
    sys: z.number(),
    Z: z.number(),
    domZ: z.number(),
    Z_setby: z.number(),
    domZ_setby: z.number(),
    nmodels: z.number(),
    nseqs: z.number(),
    n_past_msv: z.number(),
    n_past_bias: z.number(),
    n_past_vit: z.number(),
    n_past_fwd: z.number(),
    nhits: z.number(),
    nreported: z.number(),
    nincluded: z.number(),
    hit_offsets: z.union([z.array(z.number()), z.null()]),
    size: z.number().optional(),
});

export const zP7AlignmentDisplay = z.object({
    size: z.number(),
    n: z.number(),
    hmmfrom: z.number(),
    hmmto: z.number(),
    m: z.number(),
    sqfrom: z.number(),
    sqto: z.number(),
    l: z.number(),
    string_presence_flags: z.unknown(),
    rfline: z.union([z.string(), z.null()]),
    mmline: z.union([z.string(), z.null()]),
    csline: z.union([z.string(), z.null()]),
    model: z.string(),
    mline: z.string(),
    aseq: z.union([z.string(), z.null()]),
    ntseq: z.union([z.string(), z.null()]),
    ppline: z.union([z.string(), z.null()]),
    hmmname: z.string(),
    hmmacc: z.string(),
    hmmdesc: z.string(),
    sqname: z.string(),
    sqacc: z.string(),
    sqdesc: z.string(),
    identity: z.union([z.unknown(), z.null()]).optional(),
    similarity: z.union([z.unknown(), z.null()]).optional(),
});

export const zP7Domain = z.object({
    size: z.number(),
    ienv: z.number(),
    jenv: z.number(),
    iali: z.number(),
    jali: z.number(),
    iorf: z.number(),
    jorf: z.number(),
    envsc: z.number(),
    domcorrection: z.number(),
    dombias: z.number(),
    oasc: z.number(),
    bitscore: z.number(),
    lnP: z.number(),
    ievalue: z.number().optional(),
    cevalue: z.number().optional(),
    is_reported: z.boolean(),
    is_included: z.boolean(),
    scores_per_pos_length: z.number(),
    scores_per_pos: z.array(z.number()),
    alignment_display: zP7AlignmentDisplay,
    display: z.boolean().optional(),
    outcompeted: z.boolean().optional(),
    significant: z.boolean().optional(),
    uniq: z.number().optional(),
    segments: z.union([z.array(z.unknown()), z.null()]).optional(),
    predicted_active_sites: z.union([z.array(z.unknown()), z.null()]).optional(),
});

export const zP7Hit = z.object({
    index: z.number().optional(),
    size: z.number(),
    window_length: z.number(),
    sortkey: z.number(),
    score: z.number(),
    pre_score: z.number(),
    sum_score: z.number(),
    bias: z.number().optional(),
    lnP: z.number(),
    pre_lnP: z.number(),
    sum_lnP: z.number(),
    nexpected: z.number(),
    nregions: z.number(),
    nclustered: z.number(),
    noverlaps: z.number(),
    nenvelopes: z.number(),
    ndom: z.number(),
    flags: z.unknown(),
    is_reported: z.boolean().optional(),
    is_included: z.boolean().optional(),
    is_new: z.boolean().optional(),
    is_dropped: z.boolean().optional(),
    nreported: z.number(),
    nincluded: z.number(),
    best_domain: z.number(),
    seqidx: z.number(),
    subseq_start: z.number(),
    string_presence_flags: z.unknown(),
    name: z.string(),
    acc: z.union([z.string(), z.null()]),
    desc: z.union([z.string(), z.null()]),
    evalue: z.number().optional(),
    metadata: z.union([z.object({}), z.null()]).optional(),
    domains: z.union([z.array(zP7Domain), z.null()]),
});

export const zResult = z.object({
    stats: zHmmdSearchStats,
    hits: z.array(zP7Hit),
});

export const zResultResponseSchema = z.object({
    status: z.string(),
    result: z.union([zResult, z.null()]).optional(),
    page_count: z.union([z.number(), z.null()]).optional(),
});

export const zAlignmentQuerySchema = z.object({
    index: z.number().gte(0).optional().default(0),
});

export const zAlignmentResponseSchema = z.object({
    status: z.string(),
    domains: z.union([z.array(zP7Domain), z.null()]),
});

export const zDatabaseResponseSchema = z.object({
    id: z.union([z.string().max(32), z.null()]).optional(),
    type: z.string().max(16).optional().default("seq"),
    name: z.string().max(32),
    version: z.string().max(32),
    release_date: z.string().date().optional(),
    order: z.number().optional().default(-1),
});

export const zJobDetailsResponseSchema = z.object({
    task: z.object({
        status: z.string().max(50).optional().default("PENDING"),
        date_created: z.string().datetime(),
        date_done: z.string().datetime(),
    }),
    database: zDatabaseResponseSchema,
    id: z.union([z.string().uuid(), z.null()]).optional(),
    algo: z.string().max(16).optional().default("phmmer"),
    input: z.string(),
    threshold: z.string().max(16).optional().default("evalue"),
    E: z.union([z.number(), z.null()]).optional(),
    domE: z.union([z.number(), z.null()]).optional(),
    T: z.union([z.number(), z.null()]).optional(),
    domT: z.union([z.number(), z.null()]).optional(),
    incE: z.union([z.number(), z.null()]).optional(),
    incdomE: z.union([z.number(), z.null()]).optional(),
    incT: z.union([z.number(), z.null()]).optional(),
    incdomT: z.union([z.number(), z.null()]).optional(),
    popen: z.union([z.number(), z.null()]).optional(),
    pextend: z.union([z.number(), z.null()]).optional(),
    mx: z.union([z.string().max(16), z.null()]).optional(),
});

export const zTaskResultSchema = z.object({
    status: z.string().max(50).optional().default("PENDING"),
    date_created: z.string().datetime(),
    date_done: z.string().datetime(),
});

export const zAlgoChoices = z.enum(["phmmer", "hmmsearch", "hmmscan", "jackhmmer"]);

export const zSearchResponseSchema = z.object({
    id: z.string(),
});

export const zValidationErrorDetailSchema = z.object({
    type: z.string(),
    loc: z.array(z.string()),
    msg: z.string(),
});

export const zValidationErrorSchema = z.object({
    detail: z.array(zValidationErrorDetailSchema),
});

export const zSearchRequestSchema = z.object({
    database: z.string(),
    input: z.string(),
    threshold: z.string().max(16).optional().default("evalue"),
    E: z.union([z.number(), z.null()]).optional(),
    domE: z.union([z.number(), z.null()]).optional(),
    T: z.union([z.number(), z.null()]).optional(),
    domT: z.union([z.number(), z.null()]).optional(),
    incE: z.union([z.number(), z.null()]).optional(),
    incdomE: z.union([z.number(), z.null()]).optional(),
    incT: z.union([z.number(), z.null()]).optional(),
    incdomT: z.union([z.number(), z.null()]).optional(),
    popen: z.union([z.number(), z.null()]).optional(),
    pextend: z.union([z.number(), z.null()]).optional(),
    mx: z.union([z.string().max(16), z.null()]).optional(),
    with_taxonomy: z.boolean().optional().default(false),
    with_architecture: z.boolean().optional().default(false),
});

export const zJobsResponseSchema = z.object({
    task: zTaskResultSchema,
    id: z.union([z.string().uuid(), z.null()]).optional(),
    algo: z.string().max(16).optional().default("phmmer"),
});

export const zTaxonomyResponseSchema = z.object({
    id: z.union([z.number(), z.null()]).optional(),
    name: z.string().max(255),
    rank: z.string().max(255),
});

export const zTaxonomyTree: z.ZodTypeAny = z.object({
    id: z.number(),
    name: z.string(),
    hitcount: z.union([z.number(), z.null()]),
    hitdist: z.union([z.array(z.number()), z.null()]),
    children: z.union([
        z.array(
            z.lazy(() => {
                return zTaxonomyTree;
            }),
        ),
        z.null(),
    ]),
});

export const zTaxonomyTreeResponseSchema = z.object({
    status: z.string(),
    tree: z.union([zTaxonomyTree, z.null()]).optional(),
});

export const zTaxonomyDistributionGraph = z.object({
    data: z.array(z.array(z.number())),
    labels: z.array(z.string()),
    categories: z.array(z.string()),
    colors: z.array(z.string()),
});

export const zTaxonomyDistributionResponseSchema = z.object({
    status: z.string(),
    graph: z.union([zTaxonomyDistributionGraph, z.null()]).optional(),
});

export const zDownloadsQuerySchema = z.object({
    taxonomy_ids: z.array(z.number()).optional(),
    architecture: z.string().optional(),
});

export const zDownloadsResponseSchema = z.object({
    format: z.string(),
    name: z.string(),
    description: z.string(),
    status: z.string(),
    url: z.union([z.string(), z.null()]),
    size: z.union([z.number(), z.null()]),
});

export const zArchitectureApiGetArchitectureNameResponse = zArchitectureSchema;

export const zArchitectureApiGetDomainArchitecturesResponse = zArchitectureResponseSchema;

export const zArchitectureApiGetAnnotationsResponse = zArchitectureAnnotationsResponseSchema;

export const zArchitectureApiGetAllArchitecturesResponse = zArchitectureListResponseSchema;

export const zResultApiGetResultResponse = zResultResponseSchema;

export const zResultApiGetDomainsResponse = zAlignmentResponseSchema;

export const zSearchApiGetDatabasesResponse = z.array(zDatabaseResponseSchema);

export const zSearchApiGetJobDetailsResponse = zJobDetailsResponseSchema;

export const zSearchApiSearchResponse = zSearchResponseSchema;

export const zSearchApiGetJobsResponse = z.array(zJobsResponseSchema);

export const zTaxonomyApiSearchTaxonomyResponse = z.array(zTaxonomyResponseSchema);

export const zTaxonomyApiGetTaxonomyResponse = zTaxonomyResponseSchema;

export const zTaxonomyApiGetTaxonomyTreeResponse = zTaxonomyTreeResponseSchema;

export const zTaxonomyApiGetTaxonomyDistributionResponse = zTaxonomyDistributionResponseSchema;

export const zDownloadApiGenerateFileResponse = z.void();

export const zDownloadApiGetDownloadsResponse = z.array(zDownloadsResponseSchema);
