name: CI

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set API URL
        run: |
          if [[ "$GITHUB_REF" == 'refs/heads/main' ]]; then
            echo "VITE_API_URL=https://www.ebi.ac.uk/Tools/hmmer" >> $GITHUB_ENV
          else
            echo "VITE_API_URL=https://wwwdev.ebi.ac.uk/Tools/hmmer" >> $GITHUB_ENV
          fi
      - name: Build and update manifest
        uses: EBI-Metagenomics/clippy-pirate@v1
        with:
          image_repo: ${{ vars.IMAGE_REPO }}
          registry: dockerhub.ebi.ac.uk
          registry_username: ${{ secrets.EBI_GITLAB_USERNAME }}
          registry_password: ${{ secrets.EBI_GITLAB_PASSWORD }}
          manifest_repo_url: ${{ vars.GITLAB_INFRA_REPO_URL }}
          manifest_branch: ${{ vars.GITLAB_INFRA_BRANCH }}
          gitops_repo_token: ${{ secrets.GITLAB_INFRA_TOKEN }}
          overlay_path_main: sites/hmmer/overlays/prod
          overlay_path_dev: sites/hmmer/overlays/dev
          build_args: VITE_API_URL=${{ env.VITE_API_URL }}
